name: "scgpt_annotation"
namespace: "workflows/annotation"
version: "integration_build"
authors:
- name: "Dorien Roosen"
  roles:
  - "author"
  - "maintainer"
  info:
    role: "Core Team Member"
    links:
      email: "dorien@data-intuitive.com"
      github: "dorien-er"
      linkedin: "dorien-roosen"
    organizations:
    - name: "Data Intuitive"
      href: "https://www.data-intuitive.com"
      role: "Data Scientist"
- name: "Elizabeth Mlynarski"
  roles:
  - "contributor"
  info:
    role: "Contributor"
    organizations:
    - name: "Janssen R&D US"
      role: "Principal Scientist Computational Genomics"
- name: "Weiwei Schultz"
  roles:
  - "contributor"
  info:
    role: "Contributor"
    organizations:
    - name: "Janssen R&D US"
      role: "Associate Director Data Sciences"
argument_groups:
- name: "Query input"
  arguments:
  - type: "string"
    name: "--id"
    description: "ID of the sample."
    info: null
    example:
    - "foo"
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--input"
    description: "Path to the input file."
    info: null
    example:
    - "input.h5mu"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--modality"
    info: null
    default:
    - "rna"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--input_layer"
    description: "The layer of the input dataset to process if .X is not to be used.\
      \ Should contain log normalized counts.\n"
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--input_var_gene_names"
    description: "The .var field in the input (query) containing gene names; if not\
      \ provided, the var index will be used.\n"
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--input_obs_batch_label"
    description: "The .obs field in the input (query) dataset containing the batch\
      \ labels.\n"
    info: null
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
- name: "Model input"
  arguments:
  - type: "file"
    name: "--model"
    description: "The scGPT model file. \nMust be a fine-tuned model that contains\
      \ keys for checkpoints (--finetuned_checkpoints_key) and cell type label mapper(--label_mapper_key).\n"
    info: null
    example:
    - "best_model.pt"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--model_config"
    description: "The scGPT model configuration file. \n"
    info: null
    example:
    - "args.json"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--model_vocab"
    description: "The scGPT model vocabulary file.\n"
    info: null
    example:
    - "vocab.json"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--finetuned_checkpoints_key"
    description: "Key in the model file containing the pre-trained checkpoints.\n"
    info: null
    default:
    - "model_state_dict"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--label_mapper_key"
    description: "Key in the model file containing the cell type class to label mapper\
      \ dictionary.\n"
    info: null
    default:
    - "id_to_class"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
- name: "Outputs"
  arguments:
  - type: "file"
    name: "--output"
    description: "Output file path"
    info: null
    example:
    - "output.h5mu"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--output_compression"
    description: "The compression algorithm to use for the output h5mu file.\n"
    info: null
    example:
    - "gzip"
    required: false
    choices:
    - "gzip"
    - "lzf"
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--output_obs_predictions"
    description: "The name of the adata.obs column to write predicted cell type labels\
      \ to.\n"
    info: null
    default:
    - "scgpt_pred"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--output_obs_probability"
    description: "The name of the adata.obs column to write predicted cell type labels\
      \ to.\n"
    info: null
    default:
    - "scgpt_probability"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
- name: "Padding arguments"
  arguments:
  - type: "string"
    name: "--pad_token"
    description: "Token used for padding.\n"
    info: null
    default:
    - "<pad>"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "integer"
    name: "--pad_value"
    description: "The value of the padding token.\n"
    info: null
    default:
    - -2
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
- name: "HVG subset arguments"
  arguments:
  - type: "integer"
    name: "--n_hvg"
    description: "Number of highly variable genes to subset for.\n"
    info: null
    default:
    - 1200
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--hvg_flavor"
    description: "Method to be used for identifying highly variable genes. \nNote\
      \ that the default for this workflow (`cell_ranger`) is not the default method\
      \ for scanpy hvg detection (`seurat`).\n"
    info: null
    default:
    - "cell_ranger"
    required: false
    choices:
    - "cell_ranger"
    - "seurat"
    direction: "input"
    multiple: false
    multiple_sep: ";"
- name: "Tokenization arguments"
  arguments:
  - type: "integer"
    name: "--max_seq_len"
    description: "The maximum sequence length of the tokenized data.\n"
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
- name: "Embedding arguments"
  arguments:
  - type: "boolean"
    name: "--dsbn"
    description: "Apply domain-specific batch normalization\n"
    info: null
    default:
    - true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "integer"
    name: "--batch_size"
    description: "The batch size to be used for embedding inference.\n"
    info: null
    default:
    - 64
    required: false
    min: 1
    direction: "input"
    multiple: false
    multiple_sep: ";"
- name: "Binning arguments"
  arguments:
  - type: "integer"
    name: "--n_input_bins"
    description: "The number of bins to discretize the data into; When no value is\
      \ provided, data won't be binned.\n"
    info: null
    default:
    - 51
    required: false
    min: 1
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "integer"
    name: "--seed"
    description: "Seed for random number generation used for binning. If not set,\
      \ no seed is used.\n"
    info: null
    required: false
    min: 0
    direction: "input"
    multiple: false
    multiple_sep: ";"
resources:
- type: "nextflow_script"
  path: "main.nf"
  is_executable: true
  entrypoint: "run_wf"
- type: "file"
  path: "nextflow_labels.config"
  dest: "nextflow_labels.config"
description: "Cell type annotation workflow using scGPT. \nThe workflow takes a pre-processed\
  \ h5mu file as query input, and performs\n  - subsetting for HVG\n  - cross-checking\
  \ of genes with the model vocabulary\n  - binning of gene counts\n  - padding and\
  \ tokenizing of genes\n  - transformer-based cell type prediction\nNote that cell-type\
  \ prediction using scGPT is only possible using a fine-tuned scGPT model.\n"
test_resources:
- type: "nextflow_script"
  path: "test.nf"
  is_executable: true
  entrypoint: "test_wf"
- type: "file"
  path: "scgpt"
info:
  name: "scGPT Annotation"
  test_dependencies:
  - name: "scgpt_annotation_test"
    namespace: "test_workflows/annotation"
status: "enabled"
scope:
  image: "public"
  target: "public"
dependencies:
- name: "scgpt/cross_check_genes"
  repository:
    type: "local"
- name: "scgpt/binning"
  repository:
    type: "local"
- name: "feature_annotation/highly_variable_features_scanpy"
  repository:
    type: "local"
- name: "filter/do_filter"
  repository:
    type: "local"
- name: "scgpt/pad_tokenize"
  repository:
    type: "local"
- name: "scgpt/cell_type_annotation"
  alias: "scgpt_celltype_annotation"
  repository:
    type: "local"
links:
  repository: "https://github.com/openpipelines-bio/openpipeline"
  docker_registry: "ghcr.io"
runners:
- type: "nextflow"
  id: "nextflow"
  directives:
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      mem1gb: "memory = 1000000000.B"
      mem2gb: "memory = 2000000000.B"
      mem5gb: "memory = 5000000000.B"
      mem10gb: "memory = 10000000000.B"
      mem20gb: "memory = 20000000000.B"
      mem50gb: "memory = 50000000000.B"
      mem100gb: "memory = 100000000000.B"
      mem200gb: "memory = 200000000000.B"
      mem500gb: "memory = 500000000000.B"
      mem1tb: "memory = 1000000000000.B"
      mem2tb: "memory = 2000000000000.B"
      mem5tb: "memory = 5000000000000.B"
      mem10tb: "memory = 10000000000000.B"
      mem20tb: "memory = 20000000000000.B"
      mem50tb: "memory = 50000000000000.B"
      mem100tb: "memory = 100000000000000.B"
      mem200tb: "memory = 200000000000000.B"
      mem500tb: "memory = 500000000000000.B"
      mem1gib: "memory = 1073741824.B"
      mem2gib: "memory = 2147483648.B"
      mem4gib: "memory = 4294967296.B"
      mem8gib: "memory = 8589934592.B"
      mem16gib: "memory = 17179869184.B"
      mem32gib: "memory = 34359738368.B"
      mem64gib: "memory = 68719476736.B"
      mem128gib: "memory = 137438953472.B"
      mem256gib: "memory = 274877906944.B"
      mem512gib: "memory = 549755813888.B"
      mem1tib: "memory = 1099511627776.B"
      mem2tib: "memory = 2199023255552.B"
      mem4tib: "memory = 4398046511104.B"
      mem8tib: "memory = 8796093022208.B"
      mem16tib: "memory = 17592186044416.B"
      mem32tib: "memory = 35184372088832.B"
      mem64tib: "memory = 70368744177664.B"
      mem128tib: "memory = 140737488355328.B"
      mem256tib: "memory = 281474976710656.B"
      mem512tib: "memory = 562949953421312.B"
      cpu1: "cpus = 1"
      cpu2: "cpus = 2"
      cpu5: "cpus = 5"
      cpu10: "cpus = 10"
      cpu20: "cpus = 20"
      cpu50: "cpus = 50"
      cpu100: "cpus = 100"
      cpu200: "cpus = 200"
      cpu500: "cpus = 500"
      cpu1000: "cpus = 1000"
    script:
    - "includeConfig(\"nextflow_labels.config\")"
  debug: false
  container: "docker"
build_info:
  config: "src/workflows/annotation/scgpt_annotation/config.vsh.yaml"
  runner: "nextflow"
  engine: "native"
  output: "target/nextflow/workflows/annotation/scgpt_annotation"
  executable: "target/nextflow/workflows/annotation/scgpt_annotation/main.nf"
  viash_version: "0.9.3"
  git_commit: "675a8a433f9892728bd294f3221a636f31b2f597"
  git_remote: "https://github.com/openpipelines-bio/openpipeline"
  dependencies:
  - "target/nextflow/scgpt/cross_check_genes"
  - "target/nextflow/scgpt/binning"
  - "target/nextflow/feature_annotation/highly_variable_features_scanpy"
  - "target/nextflow/filter/do_filter"
  - "target/nextflow/scgpt/pad_tokenize"
  - "target/nextflow/scgpt/cell_type_annotation"
package_config:
  name: "openpipeline"
  info:
    test_resources:
    - type: "s3"
      path: "s3://openpipelines-data"
      dest: "resources_test"
  viash_version: "0.9.3"
  source: "src"
  target: "target"
  config_mods:
  - ".resources += {path: '/src/workflows/utils/labels.config', dest: 'nextflow_labels.config'}\n\
    .runners[.type == 'nextflow'].directives.tag := '$id'\n.runners[.type == 'nextflow'].config.script\
    \ := 'includeConfig(\"nextflow_labels.config\")'"
  - ".version := \"integration_build\""
  organization: "openpipelines-bio"
  links:
    repository: "https://github.com/openpipelines-bio/openpipeline"
    docker_registry: "ghcr.io"
    homepage: "https://openpipelines.bio"
    documentation: "https://openpipelines.bio/fundamentals"
    issue_tracker: "https://github.com/openpipelines-bio/openpipeline/issues"
