functionality:
  name: "vireo"
  namespace: "genetic_demux"
  version: "integration_build"
  authors:
  - name: "Xichen Wu"
    roles:
    - "author"
    info:
      role: "Contributor"
      links:
        github: "wxicu"
        linkedin: "xichen-wu"
        orcid: "0009-0008-2168-4508"
      organizations:
      - name: "Helmholtz Munich"
        href: "https://www.helmholtz-munich.de"
        role: "Student Assistant"
  argument_groups:
  - name: "Input"
    arguments:
    - type: "file"
      name: "--cell_data"
      description: "The cell genotype file in VCF format or cellSNP folder with sparse\
        \ matrices."
      info: null
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "integer"
      name: "--n_donor"
      description: "Number of donors to demultiplex; can be larger than provided in\
        \ donor_file."
      info: null
      default:
      - 2
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--vartrix_data"
      description: "The cell genotype files in vartrix outputs."
      info: null
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--donor_file"
      description: "The donor genotype file in VCF format. Please filter the sample\
        \ and region with bcftools first!"
      info: null
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--geno_tag"
      description: "The tag for donor genotype."
      info: null
      default:
      - "PL"
      required: false
      choices:
      - "GT"
      - "GP"
      - "PL"
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "boolean"
      name: "--no_doublet"
      description: "If use, not checking doublets."
      info: null
      default:
      - false
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "integer"
      name: "--n_init"
      description: "Number of random initializations, when GT needs to learn."
      info: null
      default:
      - 50
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "integer"
      name: "--extra_donor"
      description: "Number of extra donor in pre-cluster, when GT needs to learn."
      info: null
      default:
      - 0
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--extra_donorMode"
      description: "Method for searching from extra donors. size: n_cell per donor;\
        \ distance: GT distance between donors"
      info: null
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "boolean"
      name: "--force_learn_gt"
      description: "If use, treat donor GT as prior only."
      info: null
      default:
      - false
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "boolean"
      name: "--ase_mode"
      description: "If use, turn on SNP specific allelic ratio."
      info: null
      default:
      - false
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "boolean"
      name: "--no_plot"
      description: "If use, turn off plotting GT distance."
      info: null
      default:
      - false
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "integer"
      name: "--rand_seed"
      description: "Seed for random initialization"
      info: null
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--cell_range"
      description: "Range of cells to process."
      info: null
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "boolean"
      name: "--call_ambient_rnas"
      description: "If use, detect ambient RNAs in each cell."
      info: null
      default:
      - false
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  - name: "Output"
    arguments:
    - type: "file"
      name: "--output"
      alternatives:
      - "-o"
      description: "Output directory"
      info: null
      example:
      - "vireo"
      must_exist: true
      create_parent: true
      required: false
      direction: "output"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  resources:
  - type: "bash_script"
    path: "script.sh"
    is_executable: true
  - type: "file"
    path: "./src/workflows/utils/labels.config"
    dest: "nextflow_labels.config"
  description: "Vireo is primarily designed for demultiplexing cells into donors by\
    \ modelling of expressed alleles."
  test_resources:
  - type: "bash_script"
    path: "test.sh"
    is_executable: true
  - type: "file"
    path: "../../../resources_test/vireo_test_data"
  - type: "file"
    path: "src/base/openpipelinetestutils"
    dest: "openpipelinetestutils"
  info: null
  status: "enabled"
  requirements:
    commands:
    - "ps"
  set_wd_to_resources_dir: false
platforms:
- type: "docker"
  id: "docker"
  image: "python:3.10"
  target_organization: "openpipelines-bio"
  target_registry: "ghcr.io"
  target_tag: "integration_build"
  namespace_separator: "_"
  resolve_volume: "Automatic"
  chown: true
  setup_strategy: "ifneedbepullelsecachedbuild"
  target_image_source: "https://github.com/openpipelines-bio/openpipeline"
  setup:
  - type: "python"
    user: false
    pip:
    - "threadpoolctl"
    - "vireoSNP"
    upgrade: true
  entrypoint: []
  cmd: null
- type: "nextflow"
  id: "nextflow"
  directives:
    label:
    - "midmem"
    - "midcpu"
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      mem1gb: "memory = 1.GB"
      mem2gb: "memory = 2.GB"
      mem4gb: "memory = 4.GB"
      mem8gb: "memory = 8.GB"
      mem16gb: "memory = 16.GB"
      mem32gb: "memory = 32.GB"
      mem64gb: "memory = 64.GB"
      mem128gb: "memory = 128.GB"
      mem256gb: "memory = 256.GB"
      mem512gb: "memory = 512.GB"
      mem1tb: "memory = 1.TB"
      mem2tb: "memory = 2.TB"
      mem4tb: "memory = 4.TB"
      mem8tb: "memory = 8.TB"
      mem16tb: "memory = 16.TB"
      mem32tb: "memory = 32.TB"
      mem64tb: "memory = 64.TB"
      mem128tb: "memory = 128.TB"
      mem256tb: "memory = 256.TB"
      mem512tb: "memory = 512.TB"
      cpu1: "cpus = 1"
      cpu2: "cpus = 2"
      cpu5: "cpus = 5"
      cpu10: "cpus = 10"
      cpu20: "cpus = 20"
      cpu50: "cpus = 50"
      cpu100: "cpus = 100"
      cpu200: "cpus = 200"
      cpu500: "cpus = 500"
      cpu1000: "cpus = 1000"
    script:
    - "includeConfig(\"nextflow_labels.config\")"
  debug: false
  container: "docker"
info:
  config: "/home/runner/work/openpipeline/openpipeline/src/genetic_demux/vireo/config.vsh.yaml"
  platform: "nextflow"
  output: "/home/runner/work/openpipeline/openpipeline/target/nextflow/genetic_demux/vireo"
  executable: "/home/runner/work/openpipeline/openpipeline/target/nextflow/genetic_demux/vireo/vireo"
  viash_version: "0.8.5"
  git_commit: "a84d8dc8d93ad7d470a4dd809898f1c72be59535"
  git_remote: "https://github.com/openpipelines-bio/openpipeline"
