functionality:
  name: "demuxlet"
  namespace: "genetic_demux"
  version: "integration_build"
  authors:
  - name: "Xichen Wu"
    roles:
    - "author"
    info:
      role: "Contributor"
      links:
        github: "wxicu"
        linkedin: "xichen-wu"
        orcid: "0009-0008-2168-4508"
      organizations:
      - name: "Helmholtz Munich"
        href: "https://www.helmholtz-munich.de"
        role: "Student Assistant"
  argument_groups:
  - name: "Input"
    arguments:
    - type: "file"
      name: "--sam"
      description: "Input SAM/BAM/CRAM file. Must be sorted by coordinates and indexed."
      info: null
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--tag_group"
      description: "Tag representing readgroup or cell barcodes, in the case to partition\
        \ the BAM file into multiple groups. For 10x genomics, use CB."
      info: null
      default:
      - "CB"
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--tag_umi"
      description: "Tag representing UMIs. For 10x genomiucs, use UB."
      info: null
      default:
      - "UB"
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--plp"
      description: "Input pileup format. If the value is a string, it will be considered\
        \ as the path of the plp file. If the value is boolean true, it will perform\
        \ dscpileup."
      info: null
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--vcf"
      description: "Input VCF/BCF file, containing the individual genotypes (GT),\
        \ posterior probability (GP), or genotype likelihood (PL)."
      info: null
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--field"
      description: "FORMAT field to extract the genotype, likelihood, or posterior\
        \ from"
      info: null
      default:
      - "GT"
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "double"
      name: "--geno_error_offset"
      description: "Offset of genotype error rate. [error] = [offset] + [1-offset]*[coeff]*[1-r2]"
      info: null
      default:
      - 0.1
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "double"
      name: "--geno_error_coeff"
      description: "Slope of genotype error rate. [error] = [offset] + [1-offset]*[coeff]*[1-r2]"
      info: null
      default:
      - 0.0
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--r2_info"
      description: "INFO field name representing R2 value. Used for representing imputation\
        \ quality."
      info: null
      default:
      - "R2"
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "integer"
      name: "--min_mac"
      description: "Minimum minor allele frequency."
      info: null
      default:
      - 1
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "double"
      name: "--min_call_rate"
      description: "Minimum call rate."
      info: null
      default:
      - 0.5
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--alpha"
      description: "Grid of alpha to search for (default is 0.1, 0.2, 0.3, 0.4, 0.5)"
      info: null
      default:
      - "0.5"
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "double"
      name: "--doublet_prior"
      description: "Prior of doublet"
      info: null
      default:
      - 0.5
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--sm"
      description: "List of sample IDs to compare to (default: use all)."
      info: null
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--sm_list"
      description: "File containing the list of sample IDs to compare."
      info: null
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "integer"
      name: "--sam_verbose"
      description: "Verbose message frequency for SAM/BAM/CRAM."
      info: null
      default:
      - 1000000
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "integer"
      name: "--vcf_verbose"
      description: "Verbose message frequency for VCF/BCF."
      info: null
      default:
      - 1000
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "integer"
      name: "--cap_bq"
      description: "Maximum base quality (higher BQ will be capped)."
      info: null
      default:
      - 20
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "integer"
      name: "--min_bq"
      description: "Minimum base quality to consider (lower BQ will be skipped)."
      info: null
      default:
      - 13
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "integer"
      name: "--min_mq"
      description: "Minimum mapping quality to consider (lower MQ will be ignored)."
      info: null
      default:
      - 20
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "integer"
      name: "--min_td"
      description: "Minimum distance to the tail (lower will be ignored)."
      info: null
      default:
      - 0
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "integer"
      name: "--excl_flag"
      description: "SAM/BAM FLAGs to be excluded."
      info: null
      default:
      - 3844
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--group_list"
      description: "List of tag readgroup/cell barcode to consider in this run. All\
        \ other barcodes will be ignored. This is useful for parallelized run."
      info: null
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "integer"
      name: "--min_total"
      description: "Minimum number of total reads for a droplet/cell to be considered."
      info: null
      default:
      - 0
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "integer"
      name: "--min_snp"
      description: "Minimum number of SNPs with coverage for a droplet/cell to be\
        \ considered."
      info: null
      default:
      - 0
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "integer"
      name: "--min_umi"
      description: "Minimum number of UMIs for a droplet/cell to be considered."
      info: null
      default:
      - 0
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  - name: "Output"
    arguments:
    - type: "file"
      name: "--output"
      alternatives:
      - "-o"
      description: "Output directory"
      info: null
      example:
      - "demux"
      must_exist: true
      create_parent: true
      required: false
      direction: "output"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--out"
      description: "demuxlet output file prefix"
      info: null
      example:
      - "demuxlet"
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  resources:
  - type: "r_script"
    path: "script.R"
    is_executable: true
  - type: "file"
    path: "./src/workflows/utils/labels.config"
    dest: "nextflow_labels.config"
  description: "Demuxlet is a software tool to deconvolute sample identity and identify\
    \ multiplets when\nmultiple samples are pooled by barcoded single cell sequencing.\
    \ If external genotyping data\nfor each sample is available (e.g. from SNP arrays),\
    \ demuxlet would be recommended. Be careful\nthat the parameters on the github\
    \ is not in line with the newest help version.\n"
  test_resources:
  - type: "bash_script"
    path: "test.sh"
    is_executable: true
  - type: "file"
    path: "../../../resources_test/demuxafy_test_data"
  - type: "file"
    path: "src/base/openpipelinetestutils"
    dest: "openpipelinetestutils"
  info: null
  status: "enabled"
  requirements:
    commands:
    - "ps"
  set_wd_to_resources_dir: false
platforms:
- type: "docker"
  id: "docker"
  image: "ubuntu:20.04"
  target_organization: "openpipelines-bio"
  target_registry: "ghcr.io"
  target_tag: "integration_build"
  namespace_separator: "/"
  resolve_volume: "Automatic"
  chown: true
  setup_strategy: "ifneedbepullelsecachedbuild"
  target_image_source: "https://github.com/openpipelines-bio/openpipeline"
  setup:
  - type: "apt"
    packages:
    - "autoconf"
    - "wget"
    - "git"
    - "build-essential"
    - "libcurl4-openssl-dev"
    - "cmake"
    - "libbz2-dev"
    - "libssl-dev"
    - "liblzma-dev"
    - "zlib1g-dev"
    - "r-base"
    interactive: false
  - type: "docker"
    run:
    - "git clone https://github.com/samtools/htslib.git /tmp/htslib && cd /tmp/htslib\
      \ && git submodule update --init --recursive && autoreconf -i && ./configure\
      \ --prefix=/usr/local/ && make && make install"
  - type: "docker"
    run:
    - "git clone --depth 1 https://github.com/statgen/popscle.git /tmp/popscle &&\
      \ mkdir -p /tmp/popscle/build && cd /tmp/popscle/build && cmake .. && make &&\
      \ cp /tmp/popscle/bin/popscle /usr/local/bin"
  - type: "r"
    cran:
    - "readr"
    - "processx"
    - "dplyr"
    bioc_force_install: false
  entrypoint: []
  cmd: null
- type: "nextflow"
  id: "nextflow"
  directives:
    label:
    - "midmem"
    - "midcpu"
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      mem1gb: "memory = 1.GB"
      mem2gb: "memory = 2.GB"
      mem4gb: "memory = 4.GB"
      mem8gb: "memory = 8.GB"
      mem16gb: "memory = 16.GB"
      mem32gb: "memory = 32.GB"
      mem64gb: "memory = 64.GB"
      mem128gb: "memory = 128.GB"
      mem256gb: "memory = 256.GB"
      mem512gb: "memory = 512.GB"
      mem1tb: "memory = 1.TB"
      mem2tb: "memory = 2.TB"
      mem4tb: "memory = 4.TB"
      mem8tb: "memory = 8.TB"
      mem16tb: "memory = 16.TB"
      mem32tb: "memory = 32.TB"
      mem64tb: "memory = 64.TB"
      mem128tb: "memory = 128.TB"
      mem256tb: "memory = 256.TB"
      mem512tb: "memory = 512.TB"
      cpu1: "cpus = 1"
      cpu2: "cpus = 2"
      cpu5: "cpus = 5"
      cpu10: "cpus = 10"
      cpu20: "cpus = 20"
      cpu50: "cpus = 50"
      cpu100: "cpus = 100"
      cpu200: "cpus = 200"
      cpu500: "cpus = 500"
      cpu1000: "cpus = 1000"
    script:
    - "includeConfig(\"nextflow_labels.config\")"
  debug: false
  container: "docker"
info:
  config: "/home/runner/work/openpipeline/openpipeline/src/genetic_demux/demuxlet/config.vsh.yaml"
  platform: "nextflow"
  output: "/home/runner/work/openpipeline/openpipeline/target/nextflow/genetic_demux/demuxlet"
  executable: "/home/runner/work/openpipeline/openpipeline/target/nextflow/genetic_demux/demuxlet/demuxlet"
  viash_version: "0.8.5"
  git_commit: "5398a3328abe133feb126f06ce5c01c2a55ecc3f"
  git_remote: "https://github.com/openpipelines-bio/openpipeline"
