functionality:
  name: from_csv_to_h5mu
  status: disabled
  namespace: "convert"
  version: "dev"
  description: |
    Converts an csv into an h5mu file.
  authors:
    - name: Dries De Maeyer
      email: DDeMaey1@its.jnj.com
      roles: [ maintainer ]
      props: { account: ddemaey1 }
  arguments:
    - name: "--input"
      alternatives: [-i]
      type: file
      description: Input csv file
      direction: input
      required: true
      example: input.csv
    - name: "--output"
      alternatives: ["-o"]
      type: file
      description: Output h5mu file.
      direction: output
      example: output.h5mu
    - name: "--delimiter"
      alternatives: [-d]
      type: string
      description: Delimiter for the different fields in the delimited file.
      default: ","
    - name: "--use_column_names"
      type: boolean
      description: Use the first row as column names as gene names
      default: true
      required: false
  resources:
    - type: python_script
      path: ./script.py
  # test_resources:
  #   - type: python_script
  #     path: run_test.py
  #   - path: ../../../resources_test/pbmc_1k_protein_v3
platforms:
  - type: docker
    image: python:3.8
    python:
      packages:
        - scanpy~=1.9.1
        - muon
        - mudata~=0.2.0
        - anndata~=0.8.0
  - type: nextflow
    variant: vdsl3
