functionality:
  name: "conversion"
  namespace: "conversion"
  description: "A pipeline to convert different file formats to .h5mu."
  authors:
    - name: Dries Schaumont
      email: dries@data-intuitive.com
      roles: [ author, maintainer ]
      props: { github: DriesSchaumont, orcid: "0000-0002-4389-0440" }
  argument_groups:
    - name: Inputs
      arguments:
        - name: "--id"
          required: true
          type: string
          description: ID of the sample.
          example: foo
        - name: "--input"
          alternatives: [-i]
          description: Path to the sample.
          required: true
          multiple: true
          multiple_sep: ';'
          example: input.h5mu
          type: file
        - name: "--input_type"
          type: string
          required: true
          alternatives: [-t]
          description: Type of the input file
          choices: ["10xmtx", "10xh5", "h5ad"]
    - name: Conversion from h5ad
      arguments:
        - name: "--modality"
          required: false
          type: string
          multiple: true
          description: "Name of the modality where the h5ad is stored in the h5mu object."

  resources:
    - type: nextflow_script
      path: main.nf
  test_resources:
    - type: nextflow_script
      path: main.nf
      entrypoint: test_wf
