name: "cellranger_postprocessing_test"
namespace: "test_workflows/ingestion"
scope: "test"
scope: "public"
description: "This component test the output of the integration test of the cellranger postprocessing workflow."
authors:
  - __merge__: /src/authors/jakub_majercik.yaml
argument_groups:
  - name: Inputs
    arguments:
      - name: "--input"
        type: file
        required: true
        description: Path to h5mu output.
        example: foo.final.h5mu
      - name: "--input_og"
        type: file
        required: true
        description: Path to the original h5mu file.
        example: foo.h5mu
      - name: "--is_corrected"
        type: boolean
        required: true
        description: Whether the input file has been corrected.
resources:
  - type: python_script
    path: script.py
  - path: /src/utils/setup_logger.py
engines:
  - type: docker
    image: python:3.12-slim
    __merge__: /src/base/requirements/testworkflows_setup.yaml
runners:
  - type: executable
  - type: nextflow