functionality:
  name: "cellranger_multi"
  namespace: "mapping"
  version: "main_build"
  authors:
  - name: "Angela Oliveira Pisco"
    roles:
    - "author"
    info:
      role: "Contributor"
      links:
        github: "aopisco"
        orcid: "0000-0003-0142-2355"
        linkedin: "aopisco"
      organizations:
      - name: "Insitro"
        href: "https://insitro.com"
        role: "Director of Computational Biology"
      - name: "Open Problems"
        href: "https://openproblems.bio"
        role: "Core Member"
  - name: "Robrecht Cannoodt"
    roles:
    - "author"
    - "maintainer"
    info:
      role: "Core Team Member"
      links:
        email: "robrecht@data-intuitive.com"
        github: "rcannood"
        orcid: "0000-0003-3641-729X"
        linkedin: "robrechtcannoodt"
      organizations:
      - name: "Data Intuitive"
        href: "https://www.data-intuitive.com"
        role: "Data Science Engineer"
      - name: "Open Problems"
        href: "https://openproblems.bio"
        role: "Core Member"
  - name: "Dries De Maeyer"
    roles:
    - "author"
    info:
      role: "Core Team Member"
      links:
        email: "ddemaeyer@gmail.com"
        github: "ddemaeyer"
        linkedin: "dries-de-maeyer-b46a814"
      organizations:
      - name: "Janssen Pharmaceuticals"
        href: "https://www.janssen.com"
        role: "Principal Scientist"
  argument_groups:
  - name: "Input files"
    arguments:
    - type: "file"
      name: "--input"
      description: "The FASTQ files to be analyzed. FASTQ files should conform to\
        \ the naming conventions of bcl2fastq and mkfastq:\n`[Sample Name]_S[Sample\
        \ Index]_L00[Lane Number]_[Read Type]_001.fastq.gz`\n"
      info: null
      example:
      - "mysample_S1_L001_R1_001.fastq.gz"
      - "mysample_S1_L001_R2_001.fastq.gz"
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: true
      multiple_sep: ";"
      dest: "par"
    - type: "file"
      name: "--gex_reference"
      description: "Genome refence index built by Cell Ranger mkref."
      info: null
      example:
      - "reference_genome.tar.gz"
      must_exist: true
      create_parent: true
      required: true
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--vdj_reference"
      description: "VDJ refence index built by Cell Ranger mkref."
      info: null
      example:
      - "reference_vdj.tar.gz"
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--vdj_inner_enrichment_primers"
      description: "V(D)J Immune Profiling libraries: if inner enrichment primers\
        \ other than those provided \nin the 10x Genomics kits are used, they need\
        \ to be specified here as a\ntext file with one primer per line.\n"
      info: null
      example:
      - "enrichment_primers.txt"
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--feature_reference"
      description: "Path to the Feature reference CSV file, declaring Feature Barcode\
        \ constructs and associated barcodes. Required only for Antibody Capture or\
        \ CRISPR Guide Capture libraries. See https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/using/feature-bc-analysis#feature-ref\
        \ for more information."
      info: null
      example:
      - "feature_reference.csv"
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  - name: "Feature type-specific input files"
    description: "Helper functionality to allow feature type-specific input files,\
      \ without the need to specify library_type or library_id. The library_id will\
      \ be inferred from the input paths."
    arguments:
    - type: "file"
      name: "--gex_input"
      description: "The FASTQ files to be analyzed for Gene Expression. FASTQ files\
        \ should conform to the naming conventions of bcl2fastq and mkfastq:\n`[Sample\
        \ Name]_S[Sample Index]_L00[Lane Number]_[Read Type]_001.fastq.gz`\n"
      info: null
      example:
      - "mysample_S1_L001_R1_001.fastq.gz"
      - "mysample_S1_L001_R2_001.fastq.gz"
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: true
      multiple_sep: ";"
      dest: "par"
    - type: "file"
      name: "--abc_input"
      description: "The FASTQ files to be analyzed for Antibody Capture. FASTQ files\
        \ should conform to the naming conventions of bcl2fastq and mkfastq:\n`[Sample\
        \ Name]_S[Sample Index]_L00[Lane Number]_[Read Type]_001.fastq.gz`\n"
      info: null
      example:
      - "mysample_S1_L001_R1_001.fastq.gz"
      - "mysample_S1_L001_R2_001.fastq.gz"
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: true
      multiple_sep: ";"
      dest: "par"
    - type: "file"
      name: "--cgc_input"
      description: "The FASTQ files to be analyzed for CRISPR Guide Capture. FASTQ\
        \ files should conform to the naming conventions of bcl2fastq and mkfastq:\n\
        `[Sample Name]_S[Sample Index]_L00[Lane Number]_[Read Type]_001.fastq.gz`\n"
      info: null
      example:
      - "mysample_S1_L001_R1_001.fastq.gz"
      - "mysample_S1_L001_R2_001.fastq.gz"
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: true
      multiple_sep: ";"
      dest: "par"
    - type: "file"
      name: "--mux_input"
      description: "The FASTQ files to be analyzed for Multiplexing Capture. FASTQ\
        \ files should conform to the naming conventions of bcl2fastq and mkfastq:\n\
        `[Sample Name]_S[Sample Index]_L00[Lane Number]_[Read Type]_001.fastq.gz`\n"
      info: null
      example:
      - "mysample_S1_L001_R1_001.fastq.gz"
      - "mysample_S1_L001_R2_001.fastq.gz"
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: true
      multiple_sep: ";"
      dest: "par"
    - type: "file"
      name: "--vdj_input"
      description: "The FASTQ files to be analyzed for VDJ. FASTQ files should conform\
        \ to the naming conventions of bcl2fastq and mkfastq:\n`[Sample Name]_S[Sample\
        \ Index]_L00[Lane Number]_[Read Type]_001.fastq.gz`\n"
      info: null
      example:
      - "mysample_S1_L001_R1_001.fastq.gz"
      - "mysample_S1_L001_R2_001.fastq.gz"
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: true
      multiple_sep: ";"
      dest: "par"
    - type: "file"
      name: "--vdj_t_input"
      description: "The FASTQ files to be analyzed for VDJ-T. FASTQ files should conform\
        \ to the naming conventions of bcl2fastq and mkfastq:\n`[Sample Name]_S[Sample\
        \ Index]_L00[Lane Number]_[Read Type]_001.fastq.gz`\n"
      info: null
      example:
      - "mysample_S1_L001_R1_001.fastq.gz"
      - "mysample_S1_L001_R2_001.fastq.gz"
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: true
      multiple_sep: ";"
      dest: "par"
    - type: "file"
      name: "--vdj_t_gd_input"
      description: "The FASTQ files to be analyzed for VDJ-T-GD. FASTQ files should\
        \ conform to the naming conventions of bcl2fastq and mkfastq:\n`[Sample Name]_S[Sample\
        \ Index]_L00[Lane Number]_[Read Type]_001.fastq.gz`\n"
      info: null
      example:
      - "mysample_S1_L001_R1_001.fastq.gz"
      - "mysample_S1_L001_R2_001.fastq.gz"
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: true
      multiple_sep: ";"
      dest: "par"
    - type: "file"
      name: "--vdj_b_input"
      description: "The FASTQ files to be analyzed for VDJ-B. FASTQ files should conform\
        \ to the naming conventions of bcl2fastq and mkfastq:\n`[Sample Name]_S[Sample\
        \ Index]_L00[Lane Number]_[Read Type]_001.fastq.gz`\n"
      info: null
      example:
      - "mysample_S1_L001_R1_001.fastq.gz"
      - "mysample_S1_L001_R2_001.fastq.gz"
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: true
      multiple_sep: ";"
      dest: "par"
    - type: "file"
      name: "--agc_input"
      description: "The FASTQ files to be analyzed for Antigen Capture. FASTQ files\
        \ should conform to the naming conventions of bcl2fastq and mkfastq:\n`[Sample\
        \ Name]_S[Sample Index]_L00[Lane Number]_[Read Type]_001.fastq.gz`\n"
      info: null
      example:
      - "mysample_S1_L001_R1_001.fastq.gz"
      - "mysample_S1_L001_R2_001.fastq.gz"
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: true
      multiple_sep: ";"
      dest: "par"
  - name: "Library arguments"
    arguments:
    - type: "string"
      name: "--library_id"
      description: "The Illumina sample name to analyze. This must exactly match the\
        \ 'Sample Name' part of the FASTQ files specified in the `--input` argument."
      info: null
      example:
      - "mysample1"
      required: false
      direction: "input"
      multiple: true
      multiple_sep: ";"
      dest: "par"
    - type: "string"
      name: "--library_type"
      description: "The underlying feature type of the library.\nPossible values:\
        \ \"Gene Expression\", \"VDJ\", \"VDJ-T\", \"VDJ-B\", \"Antibody Capture\"\
        , \"CRISPR Guide Capture\", \"Multiplexing Capture\"\n"
      info: null
      example:
      - "Gene Expression"
      required: false
      direction: "input"
      multiple: true
      multiple_sep: ";"
      dest: "par"
    - type: "string"
      name: "--library_subsample"
      description: "Optional. The rate at which reads from the provided FASTQ files\
        \ are sampled. Must be strictly greater than 0 and less than or equal to 1."
      info: null
      example:
      - "0.5"
      required: false
      direction: "input"
      multiple: true
      multiple_sep: ";"
      dest: "par"
    - type: "string"
      name: "--library_lanes"
      description: "Lanes associated with this sample. Defaults to using all lanes."
      info: null
      example:
      - "1-4"
      required: false
      direction: "input"
      multiple: true
      multiple_sep: ";"
      dest: "par"
  - name: "Gene expression arguments"
    description: "Arguments relevant to the analysis of gene expression data."
    arguments:
    - type: "integer"
      name: "--gex_expect_cells"
      description: "Expected number of recovered cells, used as input to cell calling\
        \ algorithm."
      info: null
      example:
      - 3000
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--gex_chemistry"
      description: "Assay configuration.\n- auto: autodetect mode\n- threeprime: Single\
        \ Cell 3'\n- fiveprime: Single Cell 5'\n- SC3Pv1: Single Cell 3' v1\n- SC3Pv2:\
        \ Single Cell 3' v2\n- SC3Pv3: Single Cell 3' v3\n- SC3Pv3LT: Single Cell\
        \ 3' v3 LT\n- SC3Pv3HT: Single Cell 3' v3 HT\n- SC5P-PE: Single Cell 5' paired-end\n\
        - SC5P-R2: Single Cell 5' R2-only\n- SC-FB: Single Cell Antibody-only 3' v2\
        \ or 5'\nSee https://kb.10xgenomics.com/hc/en-us/articles/115003764132-How-does-Cell-Ranger-auto-detect-chemistry-\
        \ for more information.\n"
      info: null
      default:
      - "auto"
      required: false
      choices:
      - "auto"
      - "threeprime"
      - "fiveprime"
      - "SC3Pv1"
      - "SC3Pv2"
      - "SC3Pv3"
      - "SC3Pv3LT"
      - "SC3Pv3HT"
      - "SC5P-PE"
      - "SC5P-R2"
      - "SC-FB"
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "boolean"
      name: "--gex_secondary_analysis"
      description: "Whether or not to run the secondary analysis e.g. clustering."
      info: null
      default:
      - false
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "boolean"
      name: "--gex_generate_bam"
      description: "Whether to generate a BAM file."
      info: null
      default:
      - false
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "boolean"
      name: "--gex_include_introns"
      description: "Include intronic reads in count (default=true unless --target-panel\
        \ is specified in which case default=false)"
      info: null
      default:
      - true
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  - name: "Cell multiplexing parameters"
    description: "Arguments related to cell multiplexing."
    arguments:
    - type: "string"
      name: "--cell_multiplex_sample_id"
      description: "A name to identify a multiplexed sample. Must be alphanumeric\
        \ with hyphens and/or underscores, and less than 64 characters. Required for\
        \ Cell Multiplexing libraries."
      info: null
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--cell_multiplex_oligo_ids"
      description: "The Cell Multiplexing oligo IDs used to multiplex this sample.\
        \ If multiple CMOs were used for a sample, separate IDs with a pipe (e.g.,\
        \ CMO301|CMO302). Required for Cell Multiplexing libraries."
      info: null
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--cell_multiplex_description"
      description: "A description for the sample."
      info: null
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  - name: "Outputs"
    arguments:
    - type: "file"
      name: "--output"
      description: "The folder to store the alignment results."
      info: null
      example:
      - "/path/to/output"
      must_exist: true
      create_parent: true
      required: true
      direction: "output"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  - name: "Executor arguments"
    arguments:
    - type: "boolean_true"
      name: "--dryrun"
      description: "If true, the output directory will only contain the CWL input\
        \ files, but the pipeline itself will not be executed."
      info: null
      direction: "input"
      dest: "par"
  resources:
  - type: "python_script"
    path: "script.py"
    is_executable: true
  - type: "file"
    path: "src/utils/setup_logger.py"
  - type: "file"
    path: "./src/workflows/utils/labels.config"
    dest: "nextflow_labels.config"
  description: "Align fastq files using Cell Ranger multi."
  test_resources:
  - type: "python_script"
    path: "test.py"
    is_executable: true
  - type: "file"
    path: "resources_test/10x_5k_anticmv/raw/"
    dest: "10x_5k_anticmv/raw/"
  - type: "file"
    path: "resources_test/10x_5k_lung_crispr/raw/"
    dest: "10x_5k_lung_crispr/raw/"
  - type: "file"
    path: "resources_test/reference_gencodev41_chr1"
  - type: "file"
    path: "src/base/openpipelinetestutils"
    dest: "openpipelinetestutils"
  info: null
  status: "enabled"
  requirements:
    commands:
    - "ps"
  set_wd_to_resources_dir: false
platforms:
- type: "docker"
  id: "docker"
  image: "ghcr.io/data-intuitive/cellranger:7.0"
  target_organization: "openpipelines-bio"
  target_registry: "ghcr.io"
  target_tag: "main_build"
  namespace_separator: "/"
  resolve_volume: "Automatic"
  chown: true
  setup_strategy: "ifneedbepullelsecachedbuild"
  target_image_source: "https://github.com/openpipelines-bio/openpipeline"
  setup:
  - type: "docker"
    run:
    - "DEBIAN_FRONTEND=noninteractive apt update && \\\napt upgrade -y && apt install\
      \ -y procps && rm -rf /var/lib/apt/lists/*\n"
  - type: "python"
    user: false
    packages:
    - "pandas"
    - "pyyaml"
    upgrade: true
  test_setup:
  - type: "docker"
    copy:
    - "openpipelinetestutils /opt/openpipelinetestutils"
  - type: "python"
    user: false
    packages:
    - "/opt/openpipelinetestutils"
    upgrade: true
  - type: "python"
    user: false
    packages:
    - "viashpy==0.6.0"
    upgrade: true
  entrypoint: []
  cmd: null
- type: "nextflow"
  id: "nextflow"
  directives:
    label:
    - "veryhighmem"
    - "highcpu"
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      mem1gb: "memory = 1.GB"
      mem2gb: "memory = 2.GB"
      mem4gb: "memory = 4.GB"
      mem8gb: "memory = 8.GB"
      mem16gb: "memory = 16.GB"
      mem32gb: "memory = 32.GB"
      mem64gb: "memory = 64.GB"
      mem128gb: "memory = 128.GB"
      mem256gb: "memory = 256.GB"
      mem512gb: "memory = 512.GB"
      mem1tb: "memory = 1.TB"
      mem2tb: "memory = 2.TB"
      mem4tb: "memory = 4.TB"
      mem8tb: "memory = 8.TB"
      mem16tb: "memory = 16.TB"
      mem32tb: "memory = 32.TB"
      mem64tb: "memory = 64.TB"
      mem128tb: "memory = 128.TB"
      mem256tb: "memory = 256.TB"
      mem512tb: "memory = 512.TB"
      cpu1: "cpus = 1"
      cpu2: "cpus = 2"
      cpu5: "cpus = 5"
      cpu10: "cpus = 10"
      cpu20: "cpus = 20"
      cpu50: "cpus = 50"
      cpu100: "cpus = 100"
      cpu200: "cpus = 200"
      cpu500: "cpus = 500"
      cpu1000: "cpus = 1000"
    script:
    - "includeConfig(\"nextflow_labels.config\")"
  debug: false
  container: "docker"
info:
  config: "/home/runner/work/openpipeline/openpipeline/src/mapping/cellranger_multi/config.vsh.yaml"
  platform: "docker"
  output: "/home/runner/work/openpipeline/openpipeline/target/docker/mapping/cellranger_multi"
  executable: "/home/runner/work/openpipeline/openpipeline/target/docker/mapping/cellranger_multi/cellranger_multi"
  viash_version: "0.8.5"
  git_commit: "b679d4b551b12ad0fee0122a238ec0b536e82b42"
  git_remote: "https://github.com/openpipelines-bio/openpipeline"
