functionality:
  name: "tar_extract"
  namespace: "compression"
  version: "integration_build"
  arguments:
  - type: "file"
    name: "--input"
    alternatives:
    - "-i"
    description: "Input file"
    info: null
    example:
    - "input.tar.gz"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--output"
    alternatives:
    - "-o"
    description: "Folder to restore file(s) to."
    info: null
    example:
    - "output_folder"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "integer"
    name: "--strip_components"
    alternatives:
    - "-s"
    description: "Strip this amount of leading components from file names on extraction.\
      \ For example, to extract only 'myfile.txt' from an archive containing the structure\
      \ `this/goes/deep/myfile.txt', use 3 to strip 'this/goes/deep/'."
    info: null
    example:
    - 1
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--exclude"
    alternatives:
    - "-e"
    description: "Prevents any file or member whose name matches the shell wildcard\
      \ (pattern) from being extracted."
    info: null
    example:
    - "docs/figures"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  resources:
  - type: "bash_script"
    path: "script.sh"
    is_executable: true
  - type: "file"
    path: "./src/workflows/utils/labels.config"
    dest: "nextflow_labels.config"
  description: "Extract files from a tar archive"
  test_resources:
  - type: "bash_script"
    path: "test.sh"
    is_executable: true
  - type: "file"
    path: "../../../LICENSE"
  - type: "file"
    path: "src/base/openpipelinetestutils"
    dest: "openpipelinetestutils"
  info: null
  status: "enabled"
  requirements:
    commands:
    - "ps"
  set_wd_to_resources_dir: false
platforms:
- type: "native"
  id: "native"
- type: "docker"
  id: "docker"
  image: "ubuntu:latest"
  target_organization: "openpipelines-bio"
  target_registry: "ghcr.io"
  target_tag: "integration_build"
  namespace_separator: "/"
  resolve_volume: "Automatic"
  chown: true
  setup_strategy: "ifneedbepullelsecachedbuild"
  target_image_source: "https://github.com/openpipelines-bio/openpipeline"
  entrypoint: []
  cmd: null
info:
  config: "/home/runner/work/openpipeline/openpipeline/src/compression/tar_extract/config.vsh.yaml"
  platform: "native"
  output: "/home/runner/work/openpipeline/openpipeline/target/native/compression/tar_extract"
  executable: "/home/runner/work/openpipeline/openpipeline/target/native/compression/tar_extract/tar_extract"
  viash_version: "0.8.5"
  git_commit: "af364b79713549d5a2ed1e2beedf81f913b22448"
  git_remote: "https://github.com/openpipelines-bio/openpipeline"
