functionality:
  name: "integration"
  namespace: "multiomics"
  description: "A pipeline for demultiplexing multimodal multi-sample RNA transcriptomics data."
  authors:
    - name: Dries De Maeyer
      email: ddemaeyer@gmail.com
      roles: [ author ]
      props: { account: ddemaey1 }
    - name: Robrecht Cannoodt
      email: rcannood@gmail.com
      roles: [ author, maintainer ]
      props: { github: rcannood, orcid: "0000-0003-3641-729X" }
    - name: Dries Schaumont
      email: dries.schaumont@data-intuitive.com
      roles: [ author ]
      props: { github: DriesSchaumont, orcid: "0000-0002-4389-0440" }
  arguments:
    - name: "--id"
      required: true
      type: string
      description: ID of the sample.
      example: foo
    - name: "--input"
      required: true
      type: file
      description: Path to the sample.
      example: dataset.h5mu
    - name: "--output"
      type: file
      required: true
      direction: output
      description: Destination path to the output.
      example: output.h5mu
    - name: "--layer"
      default: "log_normalized"
      type: string
      description: use specified layer for expression values instead of the .X object from the modality.
      required: false
    - name: "--obs_covariates"
      type: string
      description: "The .obs field(s) that define the covariate(s) to regress out."
      example: ["batch", "sample"]
      multiple: true
      required: true
  resources:
    - type: nextflow_script
      path: main.nf
  test_resources:
    - type: nextflow_script
      path: main.nf
      entrypoint: test_wf