functionality:
  name: "totalvi"
  namespace: "integrate"
  version: "main_build"
  authors:
  - name: "Vladimir Shitov"
    info:
      role: "Contributor"
      links:
        email: "vladimir.shitov@helmholtz-muenchen.de"
        github: "vladimirshitov"
        orcid: "0000-0002-1960-8812"
        linkedin: "vladimir-shitov-9a659513b"
      organizations:
      - name: "Helmholtz Munich"
        href: "https://www.helmholtz-munich.de"
        role: "PhD Candidate"
  argument_groups:
  - name: "Inputs"
    arguments:
    - type: "file"
      name: "--input"
      alternatives:
      - "-i"
      description: "Input h5mu file with query data to integrate with reference."
      info: null
      must_exist: true
      create_parent: true
      required: true
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--reference"
      alternatives:
      - "-r"
      description: "Input h5mu file with reference data to train the TOTALVI model."
      info: null
      must_exist: true
      create_parent: true
      required: true
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "boolean_true"
      name: "--force_retrain"
      alternatives:
      - "-f"
      description: "If true, retrain the model and save it to reference_model_path"
      info: null
      direction: "input"
      dest: "par"
    - type: "string"
      name: "--query_modality"
      info: null
      default:
      - "rna"
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--query_proteins_modality"
      description: "Name of the modality in the input (query) h5mu file containing\
        \ protein data"
      info: null
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--reference_modality"
      info: null
      default:
      - "rna"
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--reference_proteins_modality"
      description: "Name of the modality containing proteins in the reference"
      info: null
      default:
      - "prot"
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--input_layer"
      description: "Input layer to use. If None, X is used"
      info: null
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--obs_batch"
      description: "Column name discriminating between your batches."
      info: null
      default:
      - "sample_id"
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--var_input"
      description: ".var column containing highly variable genes. By default, do not\
        \ subset genes."
      info: null
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  - name: "Outputs"
    arguments:
    - type: "file"
      name: "--output"
      alternatives:
      - "-o"
      description: "Output h5mu file."
      info: null
      must_exist: true
      create_parent: true
      required: true
      direction: "output"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--obsm_output"
      description: "In which .obsm slot to store the resulting integrated embedding."
      info: null
      default:
      - "X_integrated_totalvi"
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--obsm_normalized_rna_output"
      description: "In which .obsm slot to store the normalized RNA from TOTALVI."
      info: null
      default:
      - "X_totalvi_normalized_rna"
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--obsm_normalized_protein_output"
      description: "In which .obsm slot to store the normalized protein data from\
        \ TOTALVI."
      info: null
      default:
      - "X_totalvi_normalized_protein"
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--reference_model_path"
      description: "Directory with the reference model. If not exists, trained model\
        \ will be saved there"
      info: null
      default:
      - "totalvi_model_reference"
      must_exist: true
      create_parent: true
      required: false
      direction: "output"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--query_model_path"
      description: "Directory, where the query model will be saved"
      info: null
      default:
      - "totalvi_model_query"
      must_exist: true
      create_parent: true
      required: false
      direction: "output"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  - name: "Learning parameters"
    arguments:
    - type: "integer"
      name: "--max_epochs"
      description: "Number of passes through the dataset"
      info: null
      default:
      - 400
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "integer"
      name: "--max_query_epochs"
      description: "Number of passes through the dataset, when fine-tuning model for\
        \ query"
      info: null
      default:
      - 200
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "double"
      name: "--weight_decay"
      description: "Weight decay, when fine-tuning model for query"
      info: null
      default:
      - 0.0
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  resources:
  - type: "python_script"
    path: "script.py"
    is_executable: true
  - type: "file"
    path: "src/utils/setup_logger.py"
  - type: "file"
    path: "./src/workflows/utils/labels.config"
    dest: "nextflow_labels.config"
  description: "Performs mapping to the reference by totalvi model: https://docs.scvi-tools.org/en/stable/tutorials/notebooks/scarches_scvi_tools.html#Reference-mapping-with-TOTALVI"
  test_resources:
  - type: "python_script"
    path: "test.py"
    is_executable: true
  - type: "file"
    path: "resources_test/pbmc_1k_protein_v3/pbmc_1k_protein_v3_mms.h5mu"
  info: null
  status: "enabled"
  requirements:
    commands:
    - "ps"
  set_wd_to_resources_dir: false
platforms:
- type: "docker"
  id: "docker"
  image: "nvcr.io/nvidia/pytorch:23.09-py3"
  target_organization: "openpipelines-bio"
  target_registry: "ghcr.io"
  target_tag: "main_build"
  namespace_separator: "_"
  resolve_volume: "Automatic"
  chown: true
  setup_strategy: "ifneedbepullelsecachedbuild"
  target_image_source: "https://github.com/openpipelines-bio/openpipeline"
  setup:
  - type: "apt"
    packages:
    - "libopenblas-dev"
    - "liblapack-dev"
    - "gfortran"
    interactive: false
  - type: "python"
    user: false
    packages:
    - "anndata~=0.9.1"
    - "mudata~=0.2.3"
    - "pandas!=2.1.2"
    - "scvi-tools~=1.0.3"
    - "jaxlib<0.4.23"
    - "jax<0.4.23"
    upgrade: true
  test_setup:
  - type: "python"
    user: false
    packages:
    - "viashpy==0.6.0"
    upgrade: true
  entrypoint: []
  cmd: null
- type: "nextflow"
  id: "nextflow"
  directives:
    label:
    - "highmem"
    - "highcpu"
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      mem1gb: "memory = 1.GB"
      mem2gb: "memory = 2.GB"
      mem4gb: "memory = 4.GB"
      mem8gb: "memory = 8.GB"
      mem16gb: "memory = 16.GB"
      mem32gb: "memory = 32.GB"
      mem64gb: "memory = 64.GB"
      mem128gb: "memory = 128.GB"
      mem256gb: "memory = 256.GB"
      mem512gb: "memory = 512.GB"
      mem1tb: "memory = 1.TB"
      mem2tb: "memory = 2.TB"
      mem4tb: "memory = 4.TB"
      mem8tb: "memory = 8.TB"
      mem16tb: "memory = 16.TB"
      mem32tb: "memory = 32.TB"
      mem64tb: "memory = 64.TB"
      mem128tb: "memory = 128.TB"
      mem256tb: "memory = 256.TB"
      mem512tb: "memory = 512.TB"
      cpu1: "cpus = 1"
      cpu2: "cpus = 2"
      cpu5: "cpus = 5"
      cpu10: "cpus = 10"
      cpu20: "cpus = 20"
      cpu50: "cpus = 50"
      cpu100: "cpus = 100"
      cpu200: "cpus = 200"
      cpu500: "cpus = 500"
      cpu1000: "cpus = 1000"
    script:
    - "includeConfig(\"nextflow_labels.config\")"
  debug: false
  container: "docker"
- type: "native"
  id: "native"
info:
  config: "/home/runner/work/openpipeline/openpipeline/src/integrate/totalvi/config.vsh.yaml"
  platform: "native"
  output: "/home/runner/work/openpipeline/openpipeline/target/native/integrate/totalvi"
  executable: "/home/runner/work/openpipeline/openpipeline/target/native/integrate/totalvi/totalvi"
  viash_version: "0.8.4"
  git_commit: "cc2c92f48ac504e9fd142bf236cc0e20cdc2d2f2"
  git_remote: "https://github.com/openpipelines-bio/openpipeline"
