functionality:
  name: convert_csv_to_h5ad
  namespace: "convert"
  version: "dev"
  description: |
    Converts an csv into an h5ad file.
  authors:
    - name: Dries De Maeyer
      email: DDeMaey1@its.jnj.com
      roles: [ maintainer ]
      props: { account: ddemaey1 }
  arguments:
    - name: "--input"
      alternatives: [-i]
      type: file
      description: Input csv file
      direction: input
      required: true
      example: input.csv
    - name: "--output"
      alternatives: ["-o"]
      type: file
      description: Output h5ad file.
      direction: output
      example: output.h5ad
    - name: "--delimiter"
      alternatives: [-d]
      type: string
      description: Delimiter for the different fields in the delimited file.
      default: ","
    - name: "--use_column_names"
      type: boolean
      description: Use the first row as column names as gene names
      default: true
      required: false
    - name: "--compression"
      type: string
      description: The compression format to be used on the final h5ad object.
      default: "gzip"
  resources:
    - type: python_script
      path: ./script.py
  tests:
    - type: bash_script
      path: run_test.sh
    - path: ../../../resources/test/pbmc_1k_protein_v3
platforms:
  - type: docker
    image: python:3.8
    python:
      packages:
        - scanpy
        - loompy
  - type: nextflow
