functionality:
  name: cellranger_multi
  namespace: mapping
  description: Align fastq files using Cell Ranger multi.
  authors:
    - __merge__: /src/authors/angela_pisco.yaml
      roles: [ author ]
    - __merge__: /src/authors/robrecht_cannoodt.yaml
      roles: [ author, maintainer ]
    - __merge__: /src/authors/dries_de_maeyer.yaml
      roles: [ author ]
  argument_groups:
    - name: Input files
      arguments:
        - type: file
          name: --input
          required: false
          description: |
            The FASTQ files to be analyzed. FASTQ files should conform to the naming conventions of bcl2fastq and mkfastq:
            `[Sample Name]_S[Sample Index]_L00[Lane Number]_[Read Type]_001.fastq.gz`
          example: [ mysample_S1_L001_R1_001.fastq.gz, mysample_S1_L001_R2_001.fastq.gz ]
          multiple: true

        - name: "--gex_reference"
          type: file
          description: "Genome refence index built by Cell Ranger mkref."
          example: "reference_genome.tar.gz"
          required: true

        - name: "--vdj_reference"
          type: file
          description: "VDJ refence index built by Cell Ranger mkref."
          example: "reference_vdj.tar.gz"
          required: false

        - name: "--vdj_inner_enrichment_primers"
          type: file
          description: |
            V(D)J Immune Profiling libraries: if inner enrichment primers other than those provided 
            in the 10x Genomics kits are used, they need to be specified here as a
            text file with one primer per line.
          example: "enrichment_primers.txt"
          required: false

        - name: "--feature_reference"
          type: file
          description: "Path to the Feature reference CSV file, declaring Feature Barcode constructs and associated barcodes. Required only for Antibody Capture or CRISPR Guide Capture libraries. See https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/using/feature-bc-analysis#feature-ref for more information."
          example: "feature_reference.csv"
          required: false

    - name: Feature type-specific input files
      description: Helper functionality to allow feature type-specific input files, without the need to specify library_type or library_id. The library_id will be inferred from the input paths.
      arguments:
        - type: file
          name: --gex_input
          required: false
          description: |
            The FASTQ files to be analyzed for Gene Expression. FASTQ files should conform to the naming conventions of bcl2fastq and mkfastq:
            `[Sample Name]_S[Sample Index]_L00[Lane Number]_[Read Type]_001.fastq.gz`
          example:
            [mysample_S1_L001_R1_001.fastq.gz, mysample_S1_L001_R2_001.fastq.gz]
          multiple: true
          multiple_sep: ";"
        - type: file
          name: --abc_input
          required: false
          description: |
            The FASTQ files to be analyzed for Antibody Capture. FASTQ files should conform to the naming conventions of bcl2fastq and mkfastq:
            `[Sample Name]_S[Sample Index]_L00[Lane Number]_[Read Type]_001.fastq.gz`
          example:
            [mysample_S1_L001_R1_001.fastq.gz, mysample_S1_L001_R2_001.fastq.gz]
          multiple: true
          multiple_sep: ";"
        - type: file
          name: --cgc_input
          required: false
          description: |
            The FASTQ files to be analyzed for CRISPR Guide Capture. FASTQ files should conform to the naming conventions of bcl2fastq and mkfastq:
            `[Sample Name]_S[Sample Index]_L00[Lane Number]_[Read Type]_001.fastq.gz`
          example:
            [mysample_S1_L001_R1_001.fastq.gz, mysample_S1_L001_R2_001.fastq.gz]
          multiple: true
          multiple_sep: ";"
        - type: file
          name: --mux_input
          required: false
          description: |
            The FASTQ files to be analyzed for Multiplexing Capture. FASTQ files should conform to the naming conventions of bcl2fastq and mkfastq:
            `[Sample Name]_S[Sample Index]_L00[Lane Number]_[Read Type]_001.fastq.gz`
          example:
            [mysample_S1_L001_R1_001.fastq.gz, mysample_S1_L001_R2_001.fastq.gz]
          multiple: true
          multiple_sep: ";"
        - type: file
          name: --vdj_input
          required: false
          description: |
            The FASTQ files to be analyzed for VDJ. FASTQ files should conform to the naming conventions of bcl2fastq and mkfastq:
            `[Sample Name]_S[Sample Index]_L00[Lane Number]_[Read Type]_001.fastq.gz`
          example:
            [mysample_S1_L001_R1_001.fastq.gz, mysample_S1_L001_R2_001.fastq.gz]
          multiple: true
          multiple_sep: ";"
        - type: file
          name: --vdj_t_input
          required: false
          description: |
            The FASTQ files to be analyzed for VDJ-T. FASTQ files should conform to the naming conventions of bcl2fastq and mkfastq:
            `[Sample Name]_S[Sample Index]_L00[Lane Number]_[Read Type]_001.fastq.gz`
          example:
            [mysample_S1_L001_R1_001.fastq.gz, mysample_S1_L001_R2_001.fastq.gz]
          multiple: true
          multiple_sep: ";"
        - type: file
          name: --vdj_t_gd_input
          required: false
          description: |
            The FASTQ files to be analyzed for VDJ-T-GD. FASTQ files should conform to the naming conventions of bcl2fastq and mkfastq:
            `[Sample Name]_S[Sample Index]_L00[Lane Number]_[Read Type]_001.fastq.gz`
          example:
            [mysample_S1_L001_R1_001.fastq.gz, mysample_S1_L001_R2_001.fastq.gz]
          multiple: true
          multiple_sep: ";"
        - type: file
          name: --vdj_b_input
          required: false
          description: |
            The FASTQ files to be analyzed for VDJ-B. FASTQ files should conform to the naming conventions of bcl2fastq and mkfastq:
            `[Sample Name]_S[Sample Index]_L00[Lane Number]_[Read Type]_001.fastq.gz`
          example:
            [mysample_S1_L001_R1_001.fastq.gz, mysample_S1_L001_R2_001.fastq.gz]
          multiple: true
          multiple_sep: ";"
        - type: file
          name: --agc_input
          required: false
          description: |
            The FASTQ files to be analyzed for Antigen Capture. FASTQ files should conform to the naming conventions of bcl2fastq and mkfastq:
            `[Sample Name]_S[Sample Index]_L00[Lane Number]_[Read Type]_001.fastq.gz`
          example:
            [mysample_S1_L001_R1_001.fastq.gz, mysample_S1_L001_R2_001.fastq.gz]
          multiple: true
          multiple_sep: ";"

    - name: Library arguments
      arguments:
        - type: string
          name: --library_id
          required: false
          description: The Illumina sample name to analyze. This must exactly match the 'Sample Name' part of the FASTQ files specified in the `--input` argument.
          example: ["mysample1"]
          multiple: true
        - type: string
          name: --library_type
          required: false
          description: |
            The underlying feature type of the library.
            Possible values: "Gene Expression", "VDJ", "VDJ-T", "VDJ-B", "Antibody Capture", "CRISPR Guide Capture", "Multiplexing Capture"
          # choices doesnt appear to be working well atm
          # choices: [ "Gene Expression", "VDJ", "VDJ-T", "VDJ-B", "Antibody Capture", "CRISPR Guide Capture", "Multiplexing Capture" ]
          example: "Gene Expression"
          multiple: true
        - type: string
          name: --library_subsample
          required: false
          description: Optional. The rate at which reads from the provided FASTQ files are sampled. Must be strictly greater than 0 and less than or equal to 1.
          example: "0.5"
          multiple: true
        # NOTE: physical_library_id was not included because documentation
        # specifies that users don't typically need to interact with it.
        # - type: string
        #   name: --physical_library_id
        #   description:  Library type. NOTE: by default, the library type is detected automatically based on specified feature_types (recommended mode). Users typically do not need to include the physical_library_id column in the CSV file.
        #   example: "..."
        #   multiple: true
        #        - type: string
        - type: string
          name: --library_lanes
          required: false
          description: Lanes associated with this sample. Defaults to using all lanes.
          example: "1-4"
          multiple: true

    - name: Gene expression arguments
      description: Arguments relevant to the analysis of gene expression data.
      arguments:

        - type: integer
          name: --gex_expect_cells
          example: 3000
          description: "Expected number of recovered cells, used as input to cell calling algorithm."

        - type: string
          name: --gex_chemistry
          default: auto
          description: |
            Assay configuration.
            - auto: autodetect mode
            - threeprime: Single Cell 3'
            - fiveprime: Single Cell 5'
            - SC3Pv1: Single Cell 3' v1
            - SC3Pv2: Single Cell 3' v2
            - SC3Pv3: Single Cell 3' v3
            - SC3Pv3LT: Single Cell 3' v3 LT
            - SC3Pv3HT: Single Cell 3' v3 HT
            - SC5P-PE: Single Cell 5' paired-end
            - SC5P-R2: Single Cell 5' R2-only
            - SC-FB: Single Cell Antibody-only 3' v2 or 5'
            See https://kb.10xgenomics.com/hc/en-us/articles/115003764132-How-does-Cell-Ranger-auto-detect-chemistry- for more information.
          choices: [ auto, threeprime, fiveprime, SC3Pv1, SC3Pv2, SC3Pv3, SC3Pv3LT, SC3Pv3HT, SC5P-PE, SC5P-R2, SC-FB ] 

        - type: boolean
          name: "--gex_secondary_analysis"
          default: false
          description: Whether or not to run the secondary analysis e.g. clustering.

        - type: boolean
          name: "--gex_generate_bam"
          default: false
          description: Whether to generate a BAM file.
        
        - type: boolean
          name: "--gex_include_introns"
          default: true
          description: Include intronic reads in count (default=true unless --target-panel is specified in which case default=false)

    - name: Cell multiplexing parameters
      description: Arguments related to cell multiplexing.
      arguments:
        - type: string
          name: --cell_multiplex_sample_id
          description: A name to identify a multiplexed sample. Must be alphanumeric with hyphens and/or underscores, and less than 64 characters. Required for Cell Multiplexing libraries.
        - type: string
          name: --cell_multiplex_oligo_ids
          description: The Cell Multiplexing oligo IDs used to multiplex this sample. If multiple CMOs were used for a sample, separate IDs with a pipe (e.g., CMO301|CMO302). Required for Cell Multiplexing libraries.
        - type: string
          name: --cell_multiplex_description
          description: A description for the sample.
    
    - name: Outputs
      arguments:
        - type: file
          name: --output
          direction: output
          description: The folder to store the alignment results.
          example: "/path/to/output"
          required: true

    - name: Executor arguments
      arguments:
        - name: "--dryrun"
          type: boolean_true
          description: "If true, the output directory will only contain the CWL input files, but the pipeline itself will not be executed."
  resources:
    - type: python_script
      path: script.py
    - path: /src/utils/setup_logger.py
  test_resources:
    - type: python_script
      path: test.py
    - path: /resources_test/10x_5k_anticmv/raw/
      dest: 10x_5k_anticmv/raw/
    - path: /resources_test/10x_5k_lung_crispr/raw/
      dest: 10x_5k_lung_crispr/raw/
    - path: /resources_test/reference_gencodev41_chr1
platforms:
  - type: docker
    image: ghcr.io/data-intuitive/cellranger:7.0
    setup:
      - type: docker
        run: DEBIAN_FRONTEND=noninteractive apt update && apt upgrade -y && rm -rf /var/lib/apt/lists/*
      - type: python
        packages: 
          - pandas
          - pyyaml
    test_setup:
      - type: python
        __merge__: [ /src/base/requirements/viashpy.yaml, .]
  - type: nextflow
    directives:
      label: [ veryhighmem, highcpu ]
