name: "scanvi_scarches"
namespace: "workflows/annotation"
version: "integration_build"
authors:
- name: "Dorien Roosen"
  roles:
  - "author"
  - "maintainer"
  info:
    role: "Core Team Member"
    links:
      email: "dorien@data-intuitive.com"
      github: "dorien-er"
      linkedin: "dorien-roosen"
    organizations:
    - name: "Data Intuitive"
      href: "https://www.data-intuitive.com"
      role: "Data Scientist"
- name: "Weiwei Schultz"
  roles:
  - "contributor"
  info:
    role: "Contributor"
    organizations:
    - name: "Janssen R&D US"
      role: "Associate Director Data Sciences"
argument_groups:
- name: "Query Input"
  arguments:
  - type: "string"
    name: "--id"
    description: "ID of the sample."
    info: null
    example:
    - "foo"
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--input"
    description: "Input dataset consisting of the (unlabeled) query observations.\
      \ The dataset is expected to be pre-processed in the same way as --reference."
    info: null
    example:
    - "input.h5mu"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--modality"
    description: "Which modality to process. Should match the modality of the --reference\
      \ dataset."
    info: null
    default:
    - "rna"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--layer"
    description: "Which layer to use for integration if .X is not to be used. Should\
      \ match the layer of the --reference dataset."
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--input_obs_batch_label"
    description: "The .obs field in the input (query) dataset containing the batch\
      \ labels."
    info: null
    example:
    - "sample"
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--input_obs_size_factor"
    description: "Key in adata.obs for size factor information. Instead of using library\
      \ size as a size factor,\nthe provided size factor column will be used as offset\
      \ in the mean of the likelihood.\nAssumed to be on linear scale.\n"
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--input_obs_categorical_covariate"
    description: "Keys in adata.obs that correspond to categorical data. These covariates\
      \ can be added in\naddition to the batch covariate and are also treated as nuisance\
      \ factors\n(i.e., the model tries to minimize their effects on the latent space).\n\
      Thus, these should not be used for biologically-relevant factors that you do\
      \ _not_ want to correct for.\nImportant: the order of the categorical covariates\
      \ matters and should match the order of the covariates in the reference data.\n"
    info: null
    required: false
    direction: "input"
    multiple: true
    multiple_sep: ";"
  - type: "string"
    name: "--input_obs_continuous_covariate"
    description: "Keys in adata.obs that correspond to continuous data. These covariates\
      \ can be added in\naddition to the batch covariate and are also treated as nuisance\
      \ factors\n(i.e., the model tries to minimize their effects on the latent space).\
      \ Thus, these should not be\nused for biologically-relevant factors that you\
      \ do _not_ want to correct for.\nImportant: the order of the continuous covariates\
      \ matters and should match the order of the covariates in the reference data.\n"
    info: null
    required: false
    direction: "input"
    multiple: true
    multiple_sep: ";"
  - type: "string"
    name: "--input_var_gene_names"
    description: ".var column containing gene names. By default, use the index."
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "boolean"
    name: "--sanitize_ensembl_ids"
    description: "Whether to sanitize ensembl ids by removing version numbers."
    info: null
    default:
    - true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
- name: "Reference input"
  arguments:
  - type: "file"
    name: "--reference"
    description: "Reference dataset consisting of the labeled observations to train\
      \ the KNN classifier on. The dataset is expected to be pre-processed in the\
      \ same way as the --input query dataset."
    info: null
    example:
    - "reference.h5mu"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--reference_obs_target"
    description: "The `.obs` key containing the target labels."
    info: null
    example:
    - "cell_type"
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--reference_obs_batch_label"
    description: "The .obs field in the reference dataset containing the batch labels."
    info: null
    example:
    - "sample"
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--reference_obs_size_factor"
    description: "Key in adata.obs for size factor information. Instead of using library\
      \ size as a size factor,\nthe provided size factor column will be used as offset\
      \ in the mean of the likelihood.\nAssumed to be on linear scale.\n"
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--reference_obs_categorical_covariate"
    description: "Keys in adata.obs that correspond to categorical data. These covariates\
      \ can be added in\naddition to the batch covariate and are also treated as nuisance\
      \ factors\n(i.e., the model tries to minimize their effects on the latent space).\n\
      Thus, these should not be used for biologically-relevant factors that you do\
      \ _not_ want to correct for.\nImportant: the order of the categorical covariates\
      \ matters and should match the order of the covariates in the query data.\n"
    info: null
    required: false
    direction: "input"
    multiple: true
    multiple_sep: ";"
  - type: "string"
    name: "--reference_obs_continuous_covariate"
    description: "Keys in adata.obs that correspond to continuous data. These covariates\
      \ can be added in\naddition to the batch covariate and are also treated as nuisance\
      \ factors\n(i.e., the model tries to minimize their effects on the latent space).\
      \ Thus, these should not be\nused for biologically-relevant factors that you\
      \ do _not_ want to correct for.\nImportant: the order of the continuous covariates\
      \ matters and should match the order of the covariates in the query data.\n"
    info: null
    required: false
    direction: "input"
    multiple: true
    multiple_sep: ";"
  - type: "string"
    name: "--unlabeled_category"
    description: "Value in the --reference_obs_batch_label field that indicates unlabeled\
      \ observations\n"
    info: null
    default:
    - "Unknown"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--reference_var_hvg"
    description: ".var column containing highly variable genes. If not provided, genes\
      \ will not be subset."
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--reference_var_gene_names"
    description: ".var column containing gene names. By default, use the index."
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
- name: "scVI, scANVI and scArches training options"
  arguments:
  - type: "boolean"
    name: "--early_stopping"
    description: "Whether to perform early stopping with respect to the validation\
      \ set."
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--early_stopping_monitor"
    description: "Metric logged during validation set epoch."
    info: null
    default:
    - "elbo_validation"
    required: false
    choices:
    - "elbo_validation"
    - "reconstruction_loss_validation"
    - "kl_local_validation"
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "integer"
    name: "--early_stopping_patience"
    description: "Number of validation epochs with no improvement after which training\
      \ will be stopped."
    info: null
    default:
    - 45
    required: false
    min: 1
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "double"
    name: "--early_stopping_min_delta"
    description: "Minimum change in the monitored quantity to qualify as an improvement,\
      \ i.e. an absolute change of less than min_delta, will count as no improvement."
    info: null
    default:
    - 0.0
    required: false
    min: 0.0
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "integer"
    name: "--max_epochs"
    description: "Number of passes through the dataset, defaults to (20000 / number\
      \ of cells) * 400 or 400; whichever is smallest."
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "boolean"
    name: "--reduce_lr_on_plateau"
    description: "Whether to monitor validation loss and reduce learning rate when\
      \ validation set `lr_scheduler_metric` plateaus."
    info: null
    default:
    - true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "double"
    name: "--lr_factor"
    description: "Factor to reduce learning rate."
    info: null
    default:
    - 0.6
    required: false
    min: 0.0
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "double"
    name: "--lr_patience"
    description: "Number of epochs with no improvement after which learning rate will\
      \ be reduced."
    info: null
    default:
    - 30.0
    required: false
    min: 0.0
    direction: "input"
    multiple: false
    multiple_sep: ";"
- name: "Leiden clustering options"
  arguments:
  - type: "double"
    name: "--leiden_resolution"
    description: "Control the coarseness of the clustering. Higher values lead to\
      \ more clusters."
    info: null
    default:
    - 1.0
    required: false
    min: 0.0
    direction: "input"
    multiple: true
    multiple_sep: ";"
- name: "Neighbor classifier arguments"
  arguments:
  - type: "string"
    name: "--knn_weights"
    description: "Weight function used in prediction. Possible values are:\n`uniform`\
      \ (all points in each neighborhood are weighted equally) or \n`distance` (weight\
      \ points by the inverse of their distance)\n"
    info: null
    default:
    - "uniform"
    required: false
    choices:
    - "uniform"
    - "distance"
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "integer"
    name: "--knn_n_neighbors"
    description: "The number of neighbors to use in k-neighbor graph structure used\
      \ for fast approximate nearest neighbor search with PyNNDescent. \nLarger values\
      \ will result in more accurate search results at the cost of computation time.\n"
    info: null
    default:
    - 15
    required: false
    min: 5
    direction: "input"
    multiple: false
    multiple_sep: ";"
- name: "Outputs"
  arguments:
  - type: "file"
    name: "--output"
    description: "The query data in .h5mu format with predicted labels predicted from\
      \ the classifier trained on the reference."
    info: null
    example:
    - "output.h5mu"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--output_obs_predictions"
    description: "In which .obs slot to store the predicted labels."
    info: null
    default:
    - "scanvi_pred"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--output_obs_probability"
    description: "In which. obs slot to store the probabilities of the predicted labels."
    info: null
    default:
    - "scanvi_probabilities"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--output_obsm_integrated"
    description: "In which .obsm slot to store the integrated embedding."
    info: null
    default:
    - "X_integrated_scanvi"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--output_compression"
    description: "The compression format to be used on the output h5mu object.\n"
    info: null
    example:
    - "gzip"
    required: false
    choices:
    - "gzip"
    - "lzf"
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--output_model"
    description: "Path to the resulting scANVI model that was updated with query data."
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
resources:
- type: "nextflow_script"
  path: "main.nf"
  is_executable: true
  entrypoint: "run_wf"
- type: "file"
  path: "nextflow_labels.config"
  dest: "nextflow_labels.config"
description: "Cell type annotation workflow using ScanVI with scArches for reference\
  \ mapping."
test_resources:
- type: "nextflow_script"
  path: "test.nf"
  is_executable: true
  entrypoint: "test_wf"
- type: "file"
  path: "TS_Blood_filtered.h5mu"
- type: "file"
  path: "pbmc_1k_protein_v3_mms.h5mu"
info:
  name: "scANVI - scArches workflow"
  test_dependencies:
  - name: "scanvi_scarches_test"
    namespace: "test_workflows/annotation"
status: "enabled"
scope:
  image: "public"
  target: "public"
dependencies:
- name: "integrate/scvi"
  repository:
    type: "local"
- name: "annotate/scanvi"
  repository:
    type: "local"
- name: "integrate/scarches"
  repository:
    type: "local"
- name: "workflows/multiomics/neighbors_leiden_umap"
  repository:
    type: "local"
license: "MIT"
links:
  repository: "https://github.com/openpipelines-bio/openpipeline"
  docker_registry: "ghcr.io"
runners:
- type: "nextflow"
  id: "nextflow"
  directives:
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      mem1gb: "memory = 1000000000.B"
      mem2gb: "memory = 2000000000.B"
      mem5gb: "memory = 5000000000.B"
      mem10gb: "memory = 10000000000.B"
      mem20gb: "memory = 20000000000.B"
      mem50gb: "memory = 50000000000.B"
      mem100gb: "memory = 100000000000.B"
      mem200gb: "memory = 200000000000.B"
      mem500gb: "memory = 500000000000.B"
      mem1tb: "memory = 1000000000000.B"
      mem2tb: "memory = 2000000000000.B"
      mem5tb: "memory = 5000000000000.B"
      mem10tb: "memory = 10000000000000.B"
      mem20tb: "memory = 20000000000000.B"
      mem50tb: "memory = 50000000000000.B"
      mem100tb: "memory = 100000000000000.B"
      mem200tb: "memory = 200000000000000.B"
      mem500tb: "memory = 500000000000000.B"
      mem1gib: "memory = 1073741824.B"
      mem2gib: "memory = 2147483648.B"
      mem4gib: "memory = 4294967296.B"
      mem8gib: "memory = 8589934592.B"
      mem16gib: "memory = 17179869184.B"
      mem32gib: "memory = 34359738368.B"
      mem64gib: "memory = 68719476736.B"
      mem128gib: "memory = 137438953472.B"
      mem256gib: "memory = 274877906944.B"
      mem512gib: "memory = 549755813888.B"
      mem1tib: "memory = 1099511627776.B"
      mem2tib: "memory = 2199023255552.B"
      mem4tib: "memory = 4398046511104.B"
      mem8tib: "memory = 8796093022208.B"
      mem16tib: "memory = 17592186044416.B"
      mem32tib: "memory = 35184372088832.B"
      mem64tib: "memory = 70368744177664.B"
      mem128tib: "memory = 140737488355328.B"
      mem256tib: "memory = 281474976710656.B"
      mem512tib: "memory = 562949953421312.B"
      cpu1: "cpus = 1"
      cpu2: "cpus = 2"
      cpu5: "cpus = 5"
      cpu10: "cpus = 10"
      cpu20: "cpus = 20"
      cpu50: "cpus = 50"
      cpu100: "cpus = 100"
      cpu200: "cpus = 200"
      cpu500: "cpus = 500"
      cpu1000: "cpus = 1000"
    script:
    - "includeConfig(\"nextflow_labels.config\")"
  debug: false
  container: "docker"
build_info:
  config: "src/workflows/annotation/scanvi_scarches/config.vsh.yaml"
  runner: "nextflow"
  engine: "native"
  output: "target/nextflow/workflows/annotation/scanvi_scarches"
  executable: "target/nextflow/workflows/annotation/scanvi_scarches/main.nf"
  viash_version: "0.9.4"
  git_commit: "c1c9381c36efa93aca5fe5f518718ac629f29004"
  git_remote: "https://github.com/openpipelines-bio/openpipeline"
  dependencies:
  - "target/nextflow/integrate/scvi"
  - "target/nextflow/annotate/scanvi"
  - "target/nextflow/integrate/scarches"
  - "target/nextflow/workflows/multiomics/neighbors_leiden_umap"
package_config:
  name: "openpipeline"
  summary: "Best-practice workflows for single-cell multi-omics analyses.\n"
  description: "OpenPipelines are extensible single cell analysis pipelines for reproducible\
    \ and large-scale single cell processing using [Viash](https://viash.io) and [Nextflow](https://www.nextflow.io/).\n\
    \nIn terms of workflows, the following has been made available, but keep in mind\
    \ that\nindividual tools and functionality can be executed as standalone components\
    \ as well.\n\n  * Demultiplexing: conversion of raw sequencing data to FASTQ objects.\n\
    \  * Ingestion: Read mapping and generating a count matrix.\n  * Single sample\
    \ processing: cell filtering and doublet detection.\n  * Multisample processing:\
    \ Count transformation, normalization, QC metric calulations.\n  * Integration:\
    \ Clustering, integration and batch correction using single and multimodal methods.\n\
    \  * Downstream analysis workflows\n"
  info:
    test_resources:
    - type: "s3"
      path: "s3://openpipelines-data"
      dest: "resources_test"
    nextflow_labels_ci:
    - path: "src/workflows/utils/labels_ci.config"
      description: "Adds the correct memory and CPU labels when running on the Viash\
        \ Hub CI."
  viash_version: "0.9.4"
  source: "src"
  target: "target"
  config_mods:
  - ".resources += {path: '/src/workflows/utils/labels.config', dest: 'nextflow_labels.config'}\n\
    .runners[.type == 'nextflow'].config.script := 'includeConfig(\"nextflow_labels.config\"\
    )'"
  - ".version := \"integration_build\""
  keywords:
  - "single-cell"
  - "multimodal"
  license: "MIT"
  organization: "openpipelines-bio"
  links:
    repository: "https://github.com/openpipelines-bio/openpipeline"
    docker_registry: "ghcr.io"
    homepage: "https://openpipelines.bio"
    documentation: "https://openpipelines.bio/fundamentals"
    issue_tracker: "https://github.com/openpipelines-bio/openpipeline/issues"
