functionality:
  name: "ts_concat"
  namespace: "custom"
  authors:
    - name: Angela Pisco
      roles: [ author ]
      props: { github: aopisco, orcid: "0000-0003-0142-2355" }
    - name: Robrecht Cannoodt
      email: robrecht@data-intuitive.com
      roles: [ author, maintainer ]
      props: { github: rcannood, orcid: "0000-0003-3641-729X" }
  argument_groups:
    - name: Inputs
      arguments:
        - name: "--id"
          required: true
          type: string
          description: ID of the sample.
          example: sample
        - type: file
          name: --input
          required: true
          example: "input.h5mu"
        - type: file
          name: --input_metadata
          description: Metadata to be joined to the .obs.  
          required: true
          example: "metadata.csv"
    - name: Output parameters
      arguments:
        - name: "--output"
          required: true
          type: file
          direction: output
          description: The path to the combined h5mu output file.
          default: '$id.output.h5mu'
  resources:
    - type: nextflow_script
      path: main.nf