name: "scgpt_leiden"
namespace: "workflows/integration"
version: "integration_build"
authors:
- name: "Dorien Roosen"
  roles:
  - "maintainer"
  - "author"
  info:
    role: "Core Team Member"
    links:
      email: "dorien@data-intuitive.com"
      github: "dorien-er"
      linkedin: "dorien-roosen"
    organizations:
    - name: "Data Intuitive"
      href: "https://www.data-intuitive.com"
      role: "Data Scientist"
- name: "Elizabeth Mlynarski"
  roles:
  - "author"
  info:
    role: "Contributor"
    organizations:
    - name: "Janssen R&D US"
      role: "Principal Scientist Computational Genomics"
- name: "Weiwei Schultz"
  roles:
  - "contributor"
  info:
    role: "Contributor"
    organizations:
    - name: "Janssen R&D US"
      role: "Associate Director Data Sciences"
argument_groups:
- name: "Inputs"
  arguments:
  - type: "string"
    name: "--id"
    description: "ID of the sample."
    info: null
    example:
    - "foo"
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--input"
    description: "Path to the input file."
    info: null
    example:
    - "input.h5mu"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--modality"
    info: null
    default:
    - "rna"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--input_layer"
    description: "Mudata layer (key from layers) to use as input data for hvg subsetting\
      \ and binning; if not specified, X is used.\n"
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--var_gene_names"
    description: "The name of the adata var column containing gene names; when no\
      \ gene_name_layer is provided, the var index will be used.\n"
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--obs_batch_label"
    description: "The name of the adata obs column containing the batch labels.\n"
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
- name: "Model"
  arguments:
  - type: "file"
    name: "--model"
    description: "Path to scGPT model file.\n"
    info: null
    example:
    - "resources_test/scgpt/best_model.pt"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--model_vocab"
    description: "Path to scGPT model vocabulary file.\n"
    info: null
    example:
    - "resources_test/scgpt/vocab.json"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--model_config"
    description: "Path to scGPT model config file.\n"
    info: null
    example:
    - "args.json"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--finetuned_checkpoints_key"
    description: "Key in the model file containing the pretrained checkpoints. Only\
      \ relevant for fine-tuned models.\n"
    info: null
    example:
    - "model_state_dict"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
- name: "Outputs"
  arguments:
  - type: "file"
    name: "--output"
    description: "Output file path"
    info: null
    example:
    - "output.h5mu"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--obsm_integrated"
    description: "In which .obsm slot to store the resulting integrated embedding."
    info: null
    default:
    - "X_scgpt"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
- name: "Padding arguments"
  arguments:
  - type: "string"
    name: "--pad_token"
    description: "Token used for padding.\n"
    info: null
    default:
    - "<pad>"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "integer"
    name: "--pad_value"
    description: "The value of the padding token.\n"
    info: null
    default:
    - -2
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
- name: "HVG subset arguments"
  arguments:
  - type: "integer"
    name: "--n_hvg"
    description: "Number of highly variable genes to subset for.\n"
    info: null
    default:
    - 1200
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
- name: "Tokenization arguments"
  arguments:
  - type: "integer"
    name: "--max_seq_len"
    description: "The maximum sequence length of the tokenized data.\n"
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
- name: "Embedding arguments"
  arguments:
  - type: "boolean"
    name: "--dsbn"
    description: "Apply domain-specific batch normalization\n"
    info: null
    default:
    - true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "integer"
    name: "--batch_size"
    description: "The batch size to be used for embedding inference.\n"
    info: null
    default:
    - 64
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
- name: "Binning arguments"
  arguments:
  - type: "integer"
    name: "--n_input_bins"
    description: "The number of bins to discretize the data into; When no value is\
      \ provided, data won't be binned.\n"
    info: null
    default:
    - 51
    required: false
    min: 1
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "integer"
    name: "--seed"
    description: "Seed for random number generation used for binning. If not set,\
      \ no seed is used.\n"
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
- name: "Clustering arguments"
  arguments:
  - type: "double"
    name: "--leiden_resolution"
    description: "Control the coarseness of the clustering. Higher values lead to\
      \ more clusters."
    info: null
    default:
    - 1.0
    required: false
    direction: "input"
    multiple: true
    multiple_sep: ";"
resources:
- type: "nextflow_script"
  path: "main.nf"
  is_executable: true
  entrypoint: "run_wf"
- type: "file"
  path: "nextflow_labels.config"
  dest: "nextflow_labels.config"
description: "Run scGPT integration (cell embedding generation) followed by neighbour\
  \ calculations, leiden clustering and run umap on the result."
test_resources:
- type: "nextflow_script"
  path: "test.nf"
  is_executable: true
  entrypoint: "test_wf"
- type: "nextflow_script"
  path: "test.nf"
  is_executable: true
  entrypoint: "test_wf2"
- type: "file"
  path: "scgpt"
- type: "file"
  path: "openpipelinetestutils"
  dest: "openpipelinetestutils"
info: null
status: "enabled"
dependencies:
- name: "scgpt/cross_check_genes"
  repository:
    type: "local"
- name: "scgpt/binning"
  repository:
    type: "local"
- name: "feature_annotation/highly_variable_features_scanpy"
  repository:
    type: "local"
- name: "filter/do_filter"
  repository:
    type: "local"
- name: "scgpt/pad_tokenize"
  repository:
    type: "local"
- name: "scgpt/embedding"
  repository:
    type: "local"
- name: "dimred/umap"
  repository:
    type: "local"
- name: "neighbors/find_neighbors"
  repository:
    type: "local"
- name: "cluster/leiden"
  repository:
    type: "local"
- name: "metadata/move_obsm_to_obs"
  repository:
    type: "local"
links:
  repository: "https://github.com/openpipelines-bio/openpipeline"
  docker_registry: "ghcr.io"
runners:
- type: "nextflow"
  id: "nextflow"
  directives:
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      mem1gb: "memory = 1000000000.B"
      mem2gb: "memory = 2000000000.B"
      mem5gb: "memory = 5000000000.B"
      mem10gb: "memory = 10000000000.B"
      mem20gb: "memory = 20000000000.B"
      mem50gb: "memory = 50000000000.B"
      mem100gb: "memory = 100000000000.B"
      mem200gb: "memory = 200000000000.B"
      mem500gb: "memory = 500000000000.B"
      mem1tb: "memory = 1000000000000.B"
      mem2tb: "memory = 2000000000000.B"
      mem5tb: "memory = 5000000000000.B"
      mem10tb: "memory = 10000000000000.B"
      mem20tb: "memory = 20000000000000.B"
      mem50tb: "memory = 50000000000000.B"
      mem100tb: "memory = 100000000000000.B"
      mem200tb: "memory = 200000000000000.B"
      mem500tb: "memory = 500000000000000.B"
      mem1gib: "memory = 1073741824.B"
      mem2gib: "memory = 2147483648.B"
      mem4gib: "memory = 4294967296.B"
      mem8gib: "memory = 8589934592.B"
      mem16gib: "memory = 17179869184.B"
      mem32gib: "memory = 34359738368.B"
      mem64gib: "memory = 68719476736.B"
      mem128gib: "memory = 137438953472.B"
      mem256gib: "memory = 274877906944.B"
      mem512gib: "memory = 549755813888.B"
      mem1tib: "memory = 1099511627776.B"
      mem2tib: "memory = 2199023255552.B"
      mem4tib: "memory = 4398046511104.B"
      mem8tib: "memory = 8796093022208.B"
      mem16tib: "memory = 17592186044416.B"
      mem32tib: "memory = 35184372088832.B"
      mem64tib: "memory = 70368744177664.B"
      mem128tib: "memory = 140737488355328.B"
      mem256tib: "memory = 281474976710656.B"
      mem512tib: "memory = 562949953421312.B"
      cpu1: "cpus = 1"
      cpu2: "cpus = 2"
      cpu5: "cpus = 5"
      cpu10: "cpus = 10"
      cpu20: "cpus = 20"
      cpu50: "cpus = 50"
      cpu100: "cpus = 100"
      cpu200: "cpus = 200"
      cpu500: "cpus = 500"
      cpu1000: "cpus = 1000"
    script:
    - "includeConfig(\"nextflow_labels.config\")"
  debug: false
  container: "docker"
build_info:
  config: "src/workflows/integration/scgpt_leiden/config.vsh.yaml"
  runner: "nextflow"
  engine: "native"
  output: "target/nextflow/workflows/integration/scgpt_leiden"
  executable: "target/nextflow/workflows/integration/scgpt_leiden/main.nf"
  viash_version: "0.9.0-RC7"
  git_commit: "5214cdb04938e76cfcecbc377bb05a95c1f05276"
  git_remote: "https://github.com/openpipelines-bio/openpipeline"
  dependencies:
  - "target/nextflow/scgpt/cross_check_genes"
  - "target/nextflow/scgpt/binning"
  - "target/nextflow/feature_annotation/highly_variable_features_scanpy"
  - "target/nextflow/filter/do_filter"
  - "target/nextflow/scgpt/pad_tokenize"
  - "target/nextflow/scgpt/embedding"
  - "target/nextflow/dimred/umap"
  - "target/nextflow/neighbors/find_neighbors"
  - "target/nextflow/cluster/leiden"
  - "target/nextflow/metadata/move_obsm_to_obs"
package_config:
  name: "openpipeline"
  version: "dev"
  info:
    test_resources:
    - type: "s3"
      path: "s3://openpipelines-data"
      dest: "resources_test"
  viash_version: "0.9.0-RC7"
  source: "src"
  target: "target"
  config_mods:
  - ".test_resources += {path: '/src/base/openpipelinetestutils', dest: 'openpipelinetestutils'}\n\
    .resources += {path: '/src/workflows/utils/labels.config', dest: 'nextflow_labels.config'}\n\
    .runners[.type == 'nextflow'].directives.tag := '$id'\n.runners[.type == 'nextflow'].config.script\
    \ := 'includeConfig(\"nextflow_labels.config\")'"
  - ".version := \"integration_build\""
  organization: "openpipelines-bio"
  links:
    repository: "https://github.com/openpipelines-bio/openpipeline"
    docker_registry: "ghcr.io"
    homepage: "https://openpipelines.bio"
    documentation: "https://openpipelines.bio/fundamentals"
    issue_tracker: "https://github.com/openpipelines-bio/openpipeline/issues"
