name: "cell_type_annotation"
namespace: "scgpt"
version: "integration_build"
authors:
- name: "Dorien Roosen"
  roles:
  - "maintainer"
  - "author"
  info:
    role: "Core Team Member"
    links:
      email: "dorien@data-intuitive.com"
      github: "dorien-er"
      linkedin: "dorien-roosen"
    organizations:
    - name: "Data Intuitive"
      href: "https://www.data-intuitive.com"
      role: "Data Scientist"
- name: "Jakub Majercik"
  roles:
  - "author"
  info:
    role: "Contributor"
    links:
      email: "jakub@data-intuitive.com"
      github: "jakubmajercik"
      linkedin: "jakubmajercik"
    organizations:
    - name: "Data Intuitive"
      href: "https://www.data-intuitive.com"
      role: "Bioinformatics Engineer"
argument_groups:
- name: "Model input"
  arguments:
  - type: "file"
    name: "--model"
    description: "The model file containing checkpoints and cell type label mapper.\n"
    info: null
    example:
    - "best_model.pt"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--model_config"
    description: "The model configuration file. \n"
    info: null
    example:
    - "args.json"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--model_vocab"
    description: "Model vocabulary file directory.\n"
    info: null
    example:
    - "vocab.json"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--finetuned_checkpoints_key"
    description: "Key in the model file containing the pretrained checkpoints.\n"
    info: null
    default:
    - "model_state_dict"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--label_mapper_key"
    description: "Key in the model file containing the cell type class to label mapper\
      \ dictionary.\n"
    info: null
    default:
    - "id_to_class"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
- name: "Query input"
  arguments:
  - type: "file"
    name: "--input"
    description: "The input h5mu file containing of data that have been pre-processed\
      \ (normalized, binned, genes cross-checked and tokenized).\n"
    info: null
    example:
    - "scgpt_preprocess_ouput.h5mu"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--modality"
    info: null
    default:
    - "rna"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--obs_batch_label"
    description: "The name of the adata.obs column containing the batch labels. Required\
      \ if dsbn is set to true.\n"
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--obsm_gene_tokens"
    description: "The key of the .obsm array containing the gene token ids\n"
    info: null
    default:
    - "gene_id_tokens"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--obsm_tokenized_values"
    description: "The key of the .obsm array containing the count values of the tokenized\
      \ genes\n"
    info: null
    default:
    - "values_tokenized"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
- name: "Outputs"
  arguments:
  - type: "file"
    name: "--output"
    description: "The output mudata file.\n"
    info: null
    example:
    - "output.h5mu"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--output_compression"
    description: "The compression algorithm to use for the output h5mu file.\n"
    info: null
    example:
    - "gzip"
    default:
    - "gzip"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--output_obs_predictions"
    description: "The name of the adata.obs column to write predicted cell type labels\
      \ to.\n"
    info: null
    default:
    - "scgpt_pred"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--output_obs_probability"
    description: "The name of the adata.obs column to write the probabilities of the\
      \ predicted cell type labels to.\n"
    info: null
    default:
    - "scgpt_probability"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
- name: "Arguments"
  arguments:
  - type: "string"
    name: "--pad_token"
    description: "The padding token used in the model.\n"
    info: null
    default:
    - "<pad>"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "integer"
    name: "--pad_value"
    description: "The value of the padding.\n"
    info: null
    default:
    - -2
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "integer"
    name: "--n_input_bins"
    description: "The number of input bins.\n"
    info: null
    default:
    - 51
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "integer"
    name: "--batch_size"
    description: "The batch size. \n"
    info: null
    default:
    - 64
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "boolean"
    name: "--dsbn"
    description: "Whether to use domain-specific batch normalization.\n"
    info: null
    default:
    - true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "integer"
    name: "--seed"
    description: "Seed for random number generation. If not specified, no seed is\
      \ used.\n"
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
resources:
- type: "python_script"
  path: "script.py"
  is_executable: true
- type: "file"
  path: "setup_logger.py"
- type: "file"
  path: "nextflow_labels.config"
  dest: "nextflow_labels.config"
description: "Annotate gene expression data with cell type classes through the scGPT\
  \ model.\n"
test_resources:
- type: "python_script"
  path: "test.py"
  is_executable: true
- type: "file"
  path: "Kim2020_Lung_subset_tokenized.h5mu"
- type: "file"
  path: "best_model.pt"
- type: "file"
  path: "args.json"
- type: "file"
  path: "vocab.json"
- type: "file"
  path: "openpipelinetestutils"
  dest: "openpipelinetestutils"
info: null
status: "enabled"
links:
  repository: "https://github.com/openpipelines-bio/openpipeline"
  docker_registry: "ghcr.io"
runners:
- type: "executable"
  id: "executable"
  docker_setup_strategy: "ifneedbepullelsecachedbuild"
- type: "nextflow"
  id: "nextflow"
  directives:
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      mem1gb: "memory = 1000000000.B"
      mem2gb: "memory = 2000000000.B"
      mem5gb: "memory = 5000000000.B"
      mem10gb: "memory = 10000000000.B"
      mem20gb: "memory = 20000000000.B"
      mem50gb: "memory = 50000000000.B"
      mem100gb: "memory = 100000000000.B"
      mem200gb: "memory = 200000000000.B"
      mem500gb: "memory = 500000000000.B"
      mem1tb: "memory = 1000000000000.B"
      mem2tb: "memory = 2000000000000.B"
      mem5tb: "memory = 5000000000000.B"
      mem10tb: "memory = 10000000000000.B"
      mem20tb: "memory = 20000000000000.B"
      mem50tb: "memory = 50000000000000.B"
      mem100tb: "memory = 100000000000000.B"
      mem200tb: "memory = 200000000000000.B"
      mem500tb: "memory = 500000000000000.B"
      mem1gib: "memory = 1073741824.B"
      mem2gib: "memory = 2147483648.B"
      mem4gib: "memory = 4294967296.B"
      mem8gib: "memory = 8589934592.B"
      mem16gib: "memory = 17179869184.B"
      mem32gib: "memory = 34359738368.B"
      mem64gib: "memory = 68719476736.B"
      mem128gib: "memory = 137438953472.B"
      mem256gib: "memory = 274877906944.B"
      mem512gib: "memory = 549755813888.B"
      mem1tib: "memory = 1099511627776.B"
      mem2tib: "memory = 2199023255552.B"
      mem4tib: "memory = 4398046511104.B"
      mem8tib: "memory = 8796093022208.B"
      mem16tib: "memory = 17592186044416.B"
      mem32tib: "memory = 35184372088832.B"
      mem64tib: "memory = 70368744177664.B"
      mem128tib: "memory = 140737488355328.B"
      mem256tib: "memory = 281474976710656.B"
      mem512tib: "memory = 562949953421312.B"
      cpu1: "cpus = 1"
      cpu2: "cpus = 2"
      cpu5: "cpus = 5"
      cpu10: "cpus = 10"
      cpu20: "cpus = 20"
      cpu50: "cpus = 50"
      cpu100: "cpus = 100"
      cpu200: "cpus = 200"
      cpu500: "cpus = 500"
      cpu1000: "cpus = 1000"
    script:
    - "includeConfig(\"nextflow_labels.config\")"
  debug: false
  container: "docker"
engines:
- type: "docker"
  id: "docker"
  image: "nvcr.io/nvidia/pytorch:23.09-py3"
  target_tag: "integration_build"
  namespace_separator: "/"
  setup:
  - type: "python"
    user: false
    packages:
    - "anndata==0.10.8"
    - "mudata~=0.2.4"
    - "pandas!=2.1.2"
    - "numpy<2.0.0"
    - "scanpy~=1.9.6"
    upgrade: true
  - type: "python"
    user: false
    packages:
    - "scgpt==0.2.1"
    upgrade: true
  test_setup:
  - type: "docker"
    copy:
    - "openpipelinetestutils /opt/openpipelinetestutils"
  - type: "python"
    user: false
    packages:
    - "/opt/openpipelinetestutils"
    upgrade: true
  - type: "python"
    user: false
    packages:
    - "viashpy==0.8.0"
    upgrade: true
  - type: "python"
    user: false
    packages:
    - "scanpy~=1.9.6"
    upgrade: true
  entrypoint: []
  cmd: null
build_info:
  config: "src/scgpt/cell_type_annotation/config.vsh.yaml"
  runner: "executable"
  engine: "docker"
  output: "target/executable/scgpt/cell_type_annotation"
  executable: "target/executable/scgpt/cell_type_annotation/cell_type_annotation"
  viash_version: "0.9.0"
  git_commit: "aa031e2f96ebd69bc14217159fdf63e1ab370de7"
  git_remote: "https://github.com/openpipelines-bio/openpipeline"
package_config:
  name: "openpipeline"
  version: "dev"
  info:
    test_resources:
    - type: "s3"
      path: "s3://openpipelines-data"
      dest: "resources_test"
  viash_version: "0.9.0"
  source: "src"
  target: "target"
  config_mods:
  - ".test_resources += {path: '/src/base/openpipelinetestutils', dest: 'openpipelinetestutils'}\n\
    .resources += {path: '/src/workflows/utils/labels.config', dest: 'nextflow_labels.config'}\n\
    .runners[.type == 'nextflow'].directives.tag := '$id'\n.runners[.type == 'nextflow'].config.script\
    \ := 'includeConfig(\"nextflow_labels.config\")'"
  - ".version := \"integration_build\""
  - ".engines[.type == 'docker'].target_tag := 'integration_build'"
  organization: "openpipelines-bio"
  links:
    repository: "https://github.com/openpipelines-bio/openpipeline"
    docker_registry: "ghcr.io"
    homepage: "https://openpipelines.bio"
    documentation: "https://openpipelines.bio/fundamentals"
    issue_tracker: "https://github.com/openpipelines-bio/openpipeline/issues"
