functionality:
  name: "run_cirrocumulus"
  namespace: "interactive"
  version: "integration_build"
  arguments:
  - type: "file"
    name: "--input"
    alternatives:
    - "-i"
    description: "Directory to mount"
    info: null
    default:
    - "."
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--port"
    alternatives:
    - "-p"
    description: "Port to use"
    info: null
    default:
    - "5005"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  resources:
  - type: "bash_script"
    path: "script.sh"
    is_executable: true
  - type: "file"
    path: "./src/workflows/utils/labels.config"
    dest: "nextflow_labels.config"
  description: ""
  test_resources:
  - type: "file"
    path: "src/base/openpipelinetestutils"
    dest: "openpipelinetestutils"
  info: null
  status: "enabled"
  requirements:
    commands:
    - "ps"
  set_wd_to_resources_dir: false
platforms:
- type: "docker"
  id: "docker"
  image: "ubuntu:focal"
  target_organization: "openpipelines-bio"
  target_registry: "ghcr.io"
  target_tag: "integration_build"
  namespace_separator: "/"
  resolve_volume: "Automatic"
  chown: true
  setup_strategy: "ifneedbepullelsecachedbuild"
  run_args:
  - "-p $VIASH_PAR_PORT:$VIASH_PAR_PORT"
  target_image_source: "https://github.com/openpipelines-bio/openpipeline"
  setup:
  - type: "docker"
    run:
    - "apt update && apt upgrade -y"
  - type: "apt"
    packages:
    - "build-essential libxml2-dev python3-dev python3-pip zlib1g-dev libhdf5-dev\
      \ python-is-python3"
    interactive: false
  - type: "python"
    user: false
    packages:
    - "requests"
    - "aiohttp"
    - "cirrocumulus"
    upgrade: true
  entrypoint: []
  cmd: null
info:
  config: "/home/runner/work/openpipeline/openpipeline/src/interactive/run_cirrocumulus/config.vsh.yaml"
  platform: "docker"
  output: "/home/runner/work/openpipeline/openpipeline/target/docker/interactive/run_cirrocumulus"
  executable: "/home/runner/work/openpipeline/openpipeline/target/docker/interactive/run_cirrocumulus/run_cirrocumulus"
  viash_version: "0.8.5"
  git_commit: "111a0478c0c5c9fca7e31c3c6de8f5402d037f1a"
  git_remote: "https://github.com/openpipelines-bio/openpipeline"
