functionality:
  name: "ts_process"
  namespace: "custom"
  authors:
    - name: Angela Pisco
      roles: [ author ]
      props: { github: aopisco, orcid: "0000-0003-0142-2355" }
    - name: Robrecht Cannoodt
      email: robrecht@data-intuitive.com
      roles: [ author, maintainer ]
      props: { github: rcannood, orcid: "0000-0003-3641-729X" }
  argument_groups:
    - name: Inputs
      arguments:
        - name: "--id"
          required: true
          type: string
          description: ID of the sample.
          example: foo
        - type: file
          name: --input
          required: true
          multiple: true
          multiple_sep: ";"
          example: [ "sample_S1_L001_R1_001.fastq.gz", "sample_S1_L001_R2_001.fastq.gz" ]
          description: The fastq.gz files to align. Can also be a single directory containing fastq.gz files.
        - type: file
          name: --reference
          required: true
          description: The path to Cell Ranger reference tar.gz file.
          example: reference.tar.gz
        - type: file
          name: --output_raw
          direction: output
          default: '$id.output_raw'
          description: The output h5mu.
        - type: file
          name: --output_h5mu
          direction: output
          default: '$id.output_h5mu.h5mu'
          description: The output h5mu.
  resources:
    - type: nextflow_script
      path: main.nf