functionality:
  name: "scsplit"
  namespace: "genetic_demux"
  version: "integration_build"
  authors:
  - name: "Xichen Wu"
    roles:
    - "author"
    info:
      role: "Contributor"
      links:
        github: "wxicu"
        linkedin: "xichen-wu"
        orcid: "0009-0008-2168-4508"
      organizations:
      - name: "Helmholtz Munich"
        href: "https://www.helmholtz-munich.de"
        role: "Student Assistant"
  argument_groups:
  - name: "Input"
    arguments:
    - type: "file"
      name: "--vcf"
      description: "VCF from mixed BAM"
      info: null
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--bam"
      description: "mixed sample BAM"
      info: null
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--bar"
      description: "barcodes whitelist"
      info: null
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--tag"
      description: "tag for barcode"
      info: null
      default:
      - "CB"
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--com"
      description: "common SNVs"
      info: null
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "integer"
      name: "--num"
      description: "expected number of mixed samples"
      info: null
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "integer"
      name: "--sub"
      description: "maximum number of subpopulations in autodetect mode"
      info: null
      default:
      - 10
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "integer"
      name: "--ems"
      description: "number of EM repeats to avoid local maximum"
      info: null
      default:
      - 30
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "double"
      name: "--dbl"
      description: "correction for doublets. There will be no refinement on the results\
        \ if this optional parameter is not specified or specified percentage is less\
        \ than doublet rates detected during the run."
      info: null
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--vcf_known"
      description: "known individual genotypes to limit distinguishing variants to\
        \ available variants, so that users do not need to redo genotyping on selected\
        \ variants, otherwise any variants could be selected as distinguishing variants."
      info: null
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "boolean_true"
      name: "--geno"
      description: "generate sample genotypes based on the split result."
      info: null
      direction: "input"
      dest: "par"
  - name: "Output"
    arguments:
    - type: "file"
      name: "--output"
      alternatives:
      - "-o"
      description: "Output directory"
      info: null
      example:
      - "scSplit_out"
      must_exist: true
      create_parent: true
      required: false
      direction: "output"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--ref"
      description: "output Ref count matrix"
      info: null
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--alt"
      description: "output Alt count matrix"
      info: null
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--psc"
      description: "generated P(S|C)"
      info: null
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  resources:
  - type: "bash_script"
    path: "script.sh"
    is_executable: true
  - type: "file"
    path: "./src/workflows/utils/labels.config"
    dest: "nextflow_labels.config"
  description: "scsplit is a genotype-free demultiplexing methode of pooled single-cell\
    \ RNA-seq, using a hidden state model for identifying genetically distinct samples\
    \ within a mixed population."
  test_resources:
  - type: "bash_script"
    path: "test.sh"
    is_executable: true
  - type: "file"
    path: "../../../resources_test/demuxafy_test_data"
  - type: "file"
    path: "src/base/openpipelinetestutils"
    dest: "openpipelinetestutils"
  info: null
  status: "enabled"
  requirements:
    commands:
    - "ps"
  set_wd_to_resources_dir: false
platforms:
- type: "docker"
  id: "docker"
  image: "python:3.9"
  target_organization: "openpipelines-bio"
  target_registry: "ghcr.io"
  target_tag: "integration_build"
  namespace_separator: "/"
  resolve_volume: "Automatic"
  chown: true
  setup_strategy: "ifneedbepullelsecachedbuild"
  target_image_source: "https://github.com/openpipelines-bio/openpipeline"
  setup:
  - type: "python"
    user: false
    pip:
    - "numpy<2"
    - "pandas<2.0"
    - "pysam"
    - "setuptools<58"
    - "scikit-learn==1.1.3"
    - "scipy"
    - "statistics"
    upgrade: true
  - type: "python"
    user: false
    pip:
    - "PyVCF"
    upgrade: true
  - type: "docker"
    run:
    - "git clone https://github.com/jon-xu/scSplit && cp scSplit/scSplit /usr/local/bin\
      \ && rm -rf scSplit"
  entrypoint: []
  cmd: null
- type: "nextflow"
  id: "nextflow"
  directives:
    label:
    - "highmem"
    - "highcpu"
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      mem1gb: "memory = 1.GB"
      mem2gb: "memory = 2.GB"
      mem4gb: "memory = 4.GB"
      mem8gb: "memory = 8.GB"
      mem16gb: "memory = 16.GB"
      mem32gb: "memory = 32.GB"
      mem64gb: "memory = 64.GB"
      mem128gb: "memory = 128.GB"
      mem256gb: "memory = 256.GB"
      mem512gb: "memory = 512.GB"
      mem1tb: "memory = 1.TB"
      mem2tb: "memory = 2.TB"
      mem4tb: "memory = 4.TB"
      mem8tb: "memory = 8.TB"
      mem16tb: "memory = 16.TB"
      mem32tb: "memory = 32.TB"
      mem64tb: "memory = 64.TB"
      mem128tb: "memory = 128.TB"
      mem256tb: "memory = 256.TB"
      mem512tb: "memory = 512.TB"
      cpu1: "cpus = 1"
      cpu2: "cpus = 2"
      cpu5: "cpus = 5"
      cpu10: "cpus = 10"
      cpu20: "cpus = 20"
      cpu50: "cpus = 50"
      cpu100: "cpus = 100"
      cpu200: "cpus = 200"
      cpu500: "cpus = 500"
      cpu1000: "cpus = 1000"
    script:
    - "includeConfig(\"nextflow_labels.config\")"
  debug: false
  container: "docker"
info:
  config: "/home/runner/work/openpipeline/openpipeline/src/genetic_demux/scsplit/config.vsh.yaml"
  platform: "docker"
  output: "/home/runner/work/openpipeline/openpipeline/target/docker/genetic_demux/scsplit"
  executable: "/home/runner/work/openpipeline/openpipeline/target/docker/genetic_demux/scsplit/scsplit"
  viash_version: "0.8.6"
  git_commit: "eed2bcc2ff4444f02d262b8dadb40b75316b1ae9"
  git_remote: "https://github.com/openpipelines-bio/openpipeline"
