functionality:
  name: "full_pipeline"
  namespace: "multiomics"
  description: "A pipeline to analyse multiple multiomics samples."
  authors:
    - name: Dries Schaumont
      email: dries@data-intuitive.com
      roles: [ author, maintainer ]
      props: { github: DriesSchaumont, orcid: "0000-0002-4389-0440" }
  argument_groups:
    - name: Inputs
      arguments:
        - name: "--id"
          required: true
          type: string
          description: ID of the sample.
          example: foo
        - name: "--input"
          alternatives: [-i]
          description: Path to the sample.
          example: input.h5mu
          type: file
        - name: "--obs_covariates"
          type: string
          description: "The .obs field(s) that define the covariate(s) to regress out."
          example: ["batch", "sample"]
          multiple: true
          required: true
  resources:
    - type: nextflow_script
      path: main.nf
  test_resources:
    - type: nextflow_script
      path: main.nf
      entrypoint: test_wf
