name: "totalvi"
namespace: "integrate"
version: "integration_build"
authors:
- name: "Dorien Roosen"
  roles:
  - "author"
  - "maintainer"
  info:
    role: "Core Team Member"
    links:
      email: "dorien@data-intuitive.com"
      github: "dorien-er"
      linkedin: "dorien-roosen"
    organizations:
    - name: "Data Intuitive"
      href: "https://www.data-intuitive.com"
      role: "Data Scientist"
- name: "Weiwei Schultz"
  roles:
  - "contributor"
  info:
    role: "Contributor"
    organizations:
    - name: "Janssen R&D US"
      role: "Associate Director Data Sciences"
argument_groups:
- name: "Inputs"
  arguments:
  - type: "file"
    name: "--input"
    alternatives:
    - "-i"
    description: "Input h5mu file to be integrated."
    info: null
    example:
    - "input.h5mu"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--rna_modality"
    info: null
    default:
    - "rna"
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--prot_modality"
    description: "Name of the modality in the input (query) h5mu file containing protein\
      \ data"
    info: null
    default:
    - "prot"
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--input_layer_rna"
    description: "Input layer to use from the rna modality for gene counts. If None,\
      \ X is used"
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--input_layer_protein"
    description: "Input layer to use from the protein modality for protein counts.\
      \ If None, X is used"
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--obs_batch"
    description: "Column name discriminating between your batches."
    info: null
    default:
    - "sample_id"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--obs_size_factor"
    description: "Key in adata.obs for size factor information. Instead of using library\
      \ size as a size factor,\nthe provided size factor column will be used as offset\
      \ in the mean of the likelihood.\nAssumed to be on linear scale.\n"
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--obs_categorical_covariate"
    description: "Keys in adata.obs that correspond to categorical data. These covariates\
      \ can be added in\naddition to the batch covariate and are also treated as nuisance\
      \ factors\n(i.e., the model tries to minimize their effects on the latent space).\n\
      Thus, these should not be used for biologically-relevant factors that you do\
      \ _not_ want to correct for.\n"
    info: null
    required: false
    direction: "input"
    multiple: true
    multiple_sep: ";"
  - type: "string"
    name: "--obs_continuous_covariate"
    description: "Keys in adata.obs that correspond to continuous data. These covariates\
      \ can be added in\naddition to the batch covariate and are also treated as nuisance\
      \ factors\n(i.e., the model tries to minimize their effects on the latent space).\
      \ Thus, these should not be\nused for biologically-relevant factors that you\
      \ do _not_ want to correct for.\n"
    info: null
    required: false
    direction: "input"
    multiple: true
    multiple_sep: ";"
  - type: "string"
    name: "--var_gene_names"
    description: ".var column in the rna modality containing gene names. By default,\
      \ use mod['rna'].var_names."
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--var_protein_names"
    description: ".var column in the protein modality containing protein names. By\
      \ default, use mod['prot'].var_names."
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--var_input"
    description: ".var column containing highly variable genes. By default, do not\
      \ subset genes."
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
- name: "Data validity checks"
  arguments:
  - type: "integer"
    name: "--n_obs_min_count"
    description: "Minimum number of cells threshold ensuring that every obs_batch\
      \ category has sufficient observations (cells) for model training."
    info: null
    default:
    - 0
    required: false
    min: 0
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "integer"
    name: "--n_var_gene_min_count"
    description: "Minimum number of genes threshold ensuring that sufficient observations\
      \ (genes) are present for model training."
    info: null
    default:
    - 0
    required: false
    min: 0
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "integer"
    name: "--n_var_protein_min_count"
    description: "Minimum number of proteins threshold ensuring that sufficient observations\
      \ (genes) are present for model training."
    info: null
    default:
    - 0
    required: false
    min: 0
    direction: "input"
    multiple: false
    multiple_sep: ";"
- name: "Model arguments"
  arguments:
  - type: "integer"
    name: "--n_dimensions_latent_space"
    description: "Dimensionality of the latent space."
    info: null
    default:
    - 20
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--gene_dispersion"
    description: "Set the behavior for the dispersion for negative binomial distributions:\n\
      \  - gene: dispersion parameter of negative binomial is constant per gene across\
      \ cells\n  - gene-batch: dispersion can differ between different batches\n \
      \ - gene-label: dispersion can differ between different labels\n  - gene-cell:\
      \  dispersion can differ for every gene in every cell\n"
    info: null
    default:
    - "gene"
    required: false
    choices:
    - "gene"
    - "gene-batch"
    - "gene-label"
    - "gene-cell"
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--protein_dispersion"
    description: "Set the behavior for the dispersion for negative binomial distributions:\n\
      \  - protein: dispersion parameter of negative binomial is constant per protein\
      \ across cells\n  - protein-batch: dispersion can differ between different batches\n\
      \  - protein-label: dispersion can differ between different labels\n"
    info: null
    default:
    - "protein"
    required: false
    choices:
    - "protein"
    - "protein-batch"
    - "protein-label"
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--gene_likelihood"
    description: "Model used to generate the expression data from a count-based likelihood\
      \ distribution.\n- nb: Negative binomial distribution\n- zinb: Zero-inflated\
      \ negative binomial distribution\n"
    info: null
    default:
    - "nb"
    required: false
    choices:
    - "nb"
    - "zinb"
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--latent_distribution"
    description: "Set the latent distribution to use:\n  - normal: Normal distribution\n\
      \  - ln: Log-normal distribution (Normal( 0, 1) transformed by softmax)\n"
    info: null
    default:
    - "normal"
    required: false
    choices:
    - "normal"
    - "ln"
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "boolean"
    name: "--empirical_protein_background_prior"
    description: "Set the initialization of protein background prior empirically.\n\
      This option fits a GMM for each of 100 cells per batch and averages the distributions.\n\
      Note that even with this option set to True, this only initializes a parameter\
      \ that is learned during inference.\nIf False, randomly initializes.\nBy default,\
      \ sets this to True if greater than 10 proteins are used.\n"
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "boolean_true"
    name: "--override_missing_proteins"
    description: "If True, will not treat proteins with all 0 expression in a particular\
      \ batch as missing.\n"
    info: null
    direction: "input"
- name: "Training arguments"
  arguments:
  - type: "integer"
    name: "--max_epochs"
    description: "Number of passes through the dataset, defaults to (20000 / number\
      \ of cells) * 400 or 400; whichever is smallest."
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "boolean"
    name: "--early_stopping"
    description: "Whether to perform early stopping with respect to the validation\
      \ set."
    info: null
    default:
    - true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
- name: "Outputs"
  arguments:
  - type: "file"
    name: "--output"
    alternatives:
    - "-o"
    description: "Output h5mu file."
    info: null
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--output_model"
    description: "Directory with the reference model. If not exists, trained model\
      \ will be saved there"
    info: null
    default:
    - "totalvi_model_reference"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--obsm_output"
    description: "In which .obsm slot to store the resulting integrated embedding."
    info: null
    default:
    - "X_integrated_totalvi"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--obsm_normalized_rna_output"
    description: "In which .obsm slot to store the normalized RNA data from TOTALVI."
    info: null
    default:
    - "X_totalvi_normalized_rna"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--obsm_normalized_protein_output"
    description: "In which .obsm slot to store the normalized protein data from TOTALVI."
    info: null
    default:
    - "X_totalvi_normalized_protein"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--output_compression"
    description: "Compression format to use for the output AnnData and/or Mudata objects.\n\
      By default no compression is applied.\n"
    info: null
    example:
    - "gzip"
    required: false
    choices:
    - "gzip"
    - "lzf"
    direction: "input"
    multiple: false
    multiple_sep: ";"
resources:
- type: "python_script"
  path: "script.py"
  is_executable: true
- type: "file"
  path: "setup_logger.py"
- type: "file"
  path: "subset_vars.py"
- type: "file"
  path: "set_var_index.py"
- type: "file"
  path: "nextflow_labels.config"
  dest: "nextflow_labels.config"
description: "Performs TotalVI integration of CITE-seq and scRNA-seq data."
test_resources:
- type: "python_script"
  path: "test.py"
  is_executable: true
- type: "file"
  path: "pbmc_1k_protein_v3_mms.h5mu"
info:
  links:
    documentation: "https://docs.scvi-tools.org/en/1.3.2/tutorials/notebooks/multimodal/cite_scrna_integration_w_totalVI.html"
status: "enabled"
scope:
  image: "public"
  target: "public"
license: "MIT"
links:
  repository: "https://github.com/openpipelines-bio/openpipeline"
  docker_registry: "ghcr.io"
runners:
- type: "executable"
  id: "executable"
  docker_setup_strategy: "ifneedbepullelsecachedbuild"
- type: "nextflow"
  id: "nextflow"
  directives:
    label:
    - "highmem"
    - "highcpu"
    - "highdisk"
    - "gpu"
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      mem1gb: "memory = 1000000000.B"
      mem2gb: "memory = 2000000000.B"
      mem5gb: "memory = 5000000000.B"
      mem10gb: "memory = 10000000000.B"
      mem20gb: "memory = 20000000000.B"
      mem50gb: "memory = 50000000000.B"
      mem100gb: "memory = 100000000000.B"
      mem200gb: "memory = 200000000000.B"
      mem500gb: "memory = 500000000000.B"
      mem1tb: "memory = 1000000000000.B"
      mem2tb: "memory = 2000000000000.B"
      mem5tb: "memory = 5000000000000.B"
      mem10tb: "memory = 10000000000000.B"
      mem20tb: "memory = 20000000000000.B"
      mem50tb: "memory = 50000000000000.B"
      mem100tb: "memory = 100000000000000.B"
      mem200tb: "memory = 200000000000000.B"
      mem500tb: "memory = 500000000000000.B"
      mem1gib: "memory = 1073741824.B"
      mem2gib: "memory = 2147483648.B"
      mem4gib: "memory = 4294967296.B"
      mem8gib: "memory = 8589934592.B"
      mem16gib: "memory = 17179869184.B"
      mem32gib: "memory = 34359738368.B"
      mem64gib: "memory = 68719476736.B"
      mem128gib: "memory = 137438953472.B"
      mem256gib: "memory = 274877906944.B"
      mem512gib: "memory = 549755813888.B"
      mem1tib: "memory = 1099511627776.B"
      mem2tib: "memory = 2199023255552.B"
      mem4tib: "memory = 4398046511104.B"
      mem8tib: "memory = 8796093022208.B"
      mem16tib: "memory = 17592186044416.B"
      mem32tib: "memory = 35184372088832.B"
      mem64tib: "memory = 70368744177664.B"
      mem128tib: "memory = 140737488355328.B"
      mem256tib: "memory = 281474976710656.B"
      mem512tib: "memory = 562949953421312.B"
      cpu1: "cpus = 1"
      cpu2: "cpus = 2"
      cpu5: "cpus = 5"
      cpu10: "cpus = 10"
      cpu20: "cpus = 20"
      cpu50: "cpus = 50"
      cpu100: "cpus = 100"
      cpu200: "cpus = 200"
      cpu500: "cpus = 500"
      cpu1000: "cpus = 1000"
    script:
    - "includeConfig(\"nextflow_labels.config\")"
  debug: false
  container: "docker"
engines:
- type: "docker"
  id: "docker"
  image: "pytorch/pytorch:2.9.1-cuda12.8-cudnn9-runtime"
  target_tag: "integration_build"
  namespace_separator: "/"
  setup:
  - type: "python"
    user: false
    packages:
    - "anndata~=0.12.7"
    - "awkward"
    - "mudata~=0.3.2"
    - "scanpy~=1.11.4"
    - "scvi-tools[cuda]~=1.4.1"
    script:
    - "exec(\"try:\\n  import zarr; from importlib.metadata import version\\nexcept\
      \ ModuleNotFoundError:\\n  exit(0)\\nelse:  assert int(version(\\\"zarr\\\"\
      ).partition(\\\".\\\")[0]) > 2\")"
    upgrade: true
  test_setup:
  - type: "python"
    user: false
    packages:
    - "viashpy==0.8.0"
    upgrade: true
  entrypoint: []
  cmd: null
build_info:
  config: "src/integrate/totalvi/config.vsh.yaml"
  runner: "nextflow"
  engine: "docker"
  output: "target/nextflow/integrate/totalvi"
  executable: "target/nextflow/integrate/totalvi/main.nf"
  viash_version: "0.9.4"
  git_commit: "bf60bc0fbbbf9c4b126f72a83c18bf1bbe7dbddc"
  git_remote: "https://github.com/openpipelines-bio/openpipeline"
package_config:
  name: "openpipeline"
  summary: "Best-practice workflows for single-cell multi-omics analyses.\n"
  description: "OpenPipelines are extensible single cell analysis pipelines for reproducible\
    \ and large-scale single cell processing using [Viash](https://viash.io) and [Nextflow](https://www.nextflow.io/).\n\
    \nIn terms of workflows, the following has been made available, but keep in mind\
    \ that\nindividual tools and functionality can be executed as standalone components\
    \ as well.\n\n  * Demultiplexing: conversion of raw sequencing data to FASTQ objects.\n\
    \  * Ingestion: Read mapping and generating a count matrix.\n  * Single sample\
    \ processing: cell filtering and doublet detection.\n  * Multisample processing:\
    \ Count transformation, normalization, QC metric calulations.\n  * Integration:\
    \ Clustering, integration and batch correction using single and multimodal methods.\n\
    \  * Downstream analysis workflows\n"
  info:
    test_resources:
    - type: "s3"
      path: "s3://openpipelines-data"
      dest: "resources_test"
    nextflow_labels_ci:
    - path: "src/workflows/utils/labels_ci.config"
      description: "Adds the correct memory and CPU labels when running on the Viash\
        \ Hub CI."
  viash_version: "0.9.4"
  source: "src"
  target: "target"
  config_mods:
  - ".resources += {path: '/src/workflows/utils/labels.config', dest: 'nextflow_labels.config'}\n\
    .runners[.type == 'nextflow'].config.script := 'includeConfig(\"nextflow_labels.config\"\
    )'"
  - ".version := \"integration_build\""
  - ".engines[.type == 'docker'].target_tag := 'integration_build'"
  keywords:
  - "single-cell"
  - "multimodal"
  license: "MIT"
  organization: "openpipelines-bio"
  links:
    repository: "https://github.com/openpipelines-bio/openpipeline"
    docker_registry: "ghcr.io"
    homepage: "https://openpipelines.bio"
    documentation: "https://openpipelines.bio/fundamentals"
    issue_tracker: "https://github.com/openpipelines-bio/openpipeline/issues"
