functionality:
  name: cellranger_mkfastq
  namespace: "bcl_demux"
  version: "dev"
  description: "Run Illumina demultiplexer on sample sheets that contain 10x-specific sample index sets, and generate 10x-specific quality metrics after the demultiplex. Any bcl2fastq argument will work (except a few that are set by the pipeline to ensure proper trimming and sample indexing). The FASTQ output generated will be the same as when running bcl2fastq directly."
  authors:
    - name: Toni Verbeiren
      email: tverbeir@its.jnj.com
      roles: [ contributor ]
      props: { account: tverbeir }
    - name: Robrecht Cannoodt
      email: rcannood@gmail.com
      roles: [ maintainer, contributor ]
      props: { github: rcannood, orcid: "0000-0003-3641-729X" }
  arguments:
    # input/output args
    - name: "--input"
      alternatives: ["-i"]
      type: file
      description: Path of Illumina BCL run tar.gz or folder.
    - name: "--samplesheet"
      type: file
      description: "Path to the sample sheet. The sample sheet can either be a simple CSV with lane, sample and index columns, or an Illumina Experiment Manager-compatible sample sheet. Sample sheet indexes can refer to 10x sample index set names (e.g., SI-GA-A12)."
    - name: "--output"
      alternatives: ["-o"]
      type: file
      direction: output
      description: The output folder generated by cellranger mkfastq
      required: true
      
    # cellranger args
    - name: "--barcode_mismatches"
      type: integer
      description: "Number of allowed mismatches per index. Multiple, comma delimited, entries allowed. Each entry is applied to the corresponding index; last entry applies to all remaining indices. Accepted values: 0, 1, 2."
      default: 1
    
    # runtime args
    - name: "--memory"
      type: integer
      description: "Set max GB the pipeline may request at one time. Only applies to local jobs. Default=128. Set to '0' to use the default cellranger behaviour."
      default: 128
    - name: "--cores"
      type: integer
      description: "Set max cores the pipeline may request at one time. Only applies to local jobs. Default=32. Set to '0' to use the default cellranger behaviour."
      default: 32

  resources:
    - type: bash_script
      path: script.sh
platforms:
  - type: docker
    image: ghcr.io/data-intuitive/cellranger:6.1
  - type: nextflow
    variant: vdsl3
