functionality:
  name: "multiomics"
  namespace: "integration"
  description: "A pipeline to analyse multiple multiomics samples."
  authors:
    - name: Dries Schaumont
      email: dries.schaumont@data-intuitive.com
      roles: [ author, maintainer ]
      props: { github: DriesSchaumont, orcid: "0000-0002-4389-0440" }
  inputs:
    - name: "--id"
      required: true
      type: string
      description: ID of the sample.
      required: true
      multiple: true
      multiple_sep: ';'
      example: foo
    - name: "--input"
      alternatives: [-i]
      description: Path to 
      required: true
      multiple: true
      multiple_sep: ';'
      example: input.h5mu
  argument_groups:
    - name: Inputs
      arguments: [ id, input ]
  resources:
    - type: nextflow_script
      path: main.nf
  test_resources:
    - type: nextflow_script
      path: main.nf
      entrypoint: test_wf