functionality:
  name: "cellsnp"
  namespace: "genetic_demux"
  version: "integration_build"
  authors:
  - name: "Xichen Wu"
    roles:
    - "author"
    info:
      role: "Contributor"
      links:
        github: "wxicu"
        linkedin: "xichen-wu"
        orcid: "0009-0008-2168-4508"
      organizations:
      - name: "Helmholtz Munich"
        href: "https://www.helmholtz-munich.de"
        role: "Student Assistant"
  argument_groups:
  - name: "Input"
    arguments:
    - type: "file"
      name: "--sam_file"
      description: "Indexed sam/bam file(s), comma separated multiple samples. Mode\
        \ 1a & 2a: one sam/bam file with single cell. Mode 1b & 2b: one or multiple\
        \ bulk sam/bam files, no barcodes needed, but sample ids and regionsVCF."
      info: null
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--sam_index_file"
      description: "Input SAM/BAM Index file, problem with samFileList."
      info: null
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--sam_fileList"
      description: "A list file containing bam files, each per line, for Mode 1b &\
        \ 2b."
      info: null
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--regions_vcf"
      description: "A vcf file listing all candidate SNPs, for fetch each variants.\
        \ If None, pileup the genome. Needed for bulk samples."
      info: null
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--targets_vcf"
      description: "Similar as --regions_vcf, but the next position is accessed by\
        \ streaming rather than indexing/jumping (like -T in samtools/bcftools mpileup)."
      info: null
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--barcode_file"
      description: "A plain file listing all effective cell barcode."
      info: null
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--sample_list"
      description: "A list file containing sample IDs, each per line."
      info: null
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--sample_ids"
      description: "Comma separated sample ids."
      info: null
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "boolean_true"
      name: "--genotype"
      description: "If use, do genotyping in addition to counting."
      info: null
      direction: "input"
      dest: "par"
    - type: "boolean_true"
      name: "--gzip"
      description: "If use, the output files will be zipped into BGZF format."
      info: null
      direction: "input"
      dest: "par"
    - type: "boolean_true"
      name: "--print_skip_snps"
      description: "If use, the SNPs skipped when loading VCF will be printed."
      info: null
      direction: "input"
      dest: "par"
    - type: "string"
      name: "--chrom"
      description: "The chromosomes to use in integer format 1-22, comma separated"
      info: null
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--cell_tag"
      description: "Tag for cell barcodes, turn off with None."
      info: null
      default:
      - "CB"
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--umi_tag"
      description: "Tag for UMI: UR, Auto, None. For Auto mode, use UR if barcodes\
        \ is inputted, otherwise use None. None mode means no UMI but read counts."
      info: null
      default:
      - "Auto"
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "integer"
      name: "--min_count"
      description: "Minimum aggragated count."
      info: null
      default:
      - 20
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "double"
      name: "--min_maf"
      description: "Minimum minor allele frequency."
      info: null
      default:
      - 0.0
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "boolean_true"
      name: "--doublet_gl"
      description: "If use, keep doublet GT likelihood, i.e., GT=0.5 and GT=1.5."
      info: null
      direction: "input"
      dest: "par"
    - type: "string"
      name: "--incl_flag"
      description: "Required flags: skip reads with all mask bits unset."
      info: null
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--excl_flag"
      description: "Filter flags: skip reads with any mask bits set [UNMAP,SECONDARY,QCFAIL\
        \ (when use UMI) or UNMAP,SECONDARY,QCFAIL,DUP (otherwise)]"
      info: null
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "boolean_true"
      name: "--count_orphan"
      description: "If use, do not skip anomalous read pairs."
      info: null
      direction: "input"
      dest: "par"
    - type: "integer"
      name: "--min_mapq"
      description: "Minimum MAPQ for read filtering."
      info: null
      default:
      - 20
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "integer"
      name: "--min_len"
      description: "Minimum mapped length for read filtering."
      info: null
      default:
      - 30
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  - name: "Output"
    arguments:
    - type: "file"
      name: "--output"
      alternatives:
      - "--outDir"
      description: "Output directory for VCF and sparse matrices."
      info: null
      example:
      - "cellsnp_out"
      must_exist: true
      create_parent: true
      required: false
      direction: "output"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  resources:
  - type: "bash_script"
    path: "script.sh"
    is_executable: true
  - type: "file"
    path: "./src/workflows/utils/labels.config"
    dest: "nextflow_labels.config"
  description: "cellSNP aims to pileup the expressed alleles in single-cell or bulk\
    \ RNA-seq data. It can be directly used for donor deconvolution in multiplexed\
    \ single-cell RNA-seq data, particularly with vireo."
  test_resources:
  - type: "bash_script"
    path: "test.sh"
    is_executable: true
  - type: "file"
    path: "../../../resources_test/demuxafy_test_data"
  - type: "file"
    path: "src/base/openpipelinetestutils"
    dest: "openpipelinetestutils"
  info: null
  status: "enabled"
  requirements:
    commands:
    - "ps"
  set_wd_to_resources_dir: false
platforms:
- type: "docker"
  id: "docker"
  image: "ubuntu:latest"
  target_organization: "openpipelines-bio"
  target_registry: "ghcr.io"
  target_tag: "integration_build"
  namespace_separator: "_"
  resolve_volume: "Automatic"
  chown: true
  setup_strategy: "ifneedbepullelsecachedbuild"
  target_image_source: "https://github.com/openpipelines-bio/openpipeline"
  setup:
  - type: "apt"
    packages:
    - "wget"
    - "gcc"
    - "zlib1g"
    - "make"
    - "libbz2-dev"
    - "zlib1g-dev"
    - "libncurses5-dev"
    - "liblzma-dev"
    - "autoconf"
    - "automake"
    - "perl"
    - "libcurl4-gnutls-dev"
    - "libssl-dev"
    - "git"
    - "bzip2"
    interactive: false
  - type: "docker"
    run:
    - "wget https://github.com/samtools/htslib/releases/download/1.16/htslib-1.16.tar.bz2\
      \ -O htslib.tar.bz2 && tar -xjvf htslib.tar.bz2 && cd htslib-1.16 && make &&\
      \ make install"
  - type: "docker"
    run:
    - "git clone https://github.com/single-cell-genetics/cellsnp-lite.git && cd cellsnp-lite\
      \ && autoreconf -iv && ./configure --with-htslib=/htslib-1.16 && make && make\
      \ install"
  entrypoint: []
  cmd: null
- type: "nextflow"
  id: "nextflow"
  directives:
    label:
    - "highmem"
    - "highcpu"
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      mem1gb: "memory = 1.GB"
      mem2gb: "memory = 2.GB"
      mem4gb: "memory = 4.GB"
      mem8gb: "memory = 8.GB"
      mem16gb: "memory = 16.GB"
      mem32gb: "memory = 32.GB"
      mem64gb: "memory = 64.GB"
      mem128gb: "memory = 128.GB"
      mem256gb: "memory = 256.GB"
      mem512gb: "memory = 512.GB"
      mem1tb: "memory = 1.TB"
      mem2tb: "memory = 2.TB"
      mem4tb: "memory = 4.TB"
      mem8tb: "memory = 8.TB"
      mem16tb: "memory = 16.TB"
      mem32tb: "memory = 32.TB"
      mem64tb: "memory = 64.TB"
      mem128tb: "memory = 128.TB"
      mem256tb: "memory = 256.TB"
      mem512tb: "memory = 512.TB"
      cpu1: "cpus = 1"
      cpu2: "cpus = 2"
      cpu5: "cpus = 5"
      cpu10: "cpus = 10"
      cpu20: "cpus = 20"
      cpu50: "cpus = 50"
      cpu100: "cpus = 100"
      cpu200: "cpus = 200"
      cpu500: "cpus = 500"
      cpu1000: "cpus = 1000"
    script:
    - "includeConfig(\"nextflow_labels.config\")"
  debug: false
  container: "docker"
info:
  config: "/home/runner/work/openpipeline/openpipeline/src/genetic_demux/cellsnp/config.vsh.yaml"
  platform: "docker"
  output: "/home/runner/work/openpipeline/openpipeline/target/docker/genetic_demux/cellsnp"
  executable: "/home/runner/work/openpipeline/openpipeline/target/docker/genetic_demux/cellsnp/cellsnp"
  viash_version: "0.8.5"
  git_commit: "cdcdec8e4e4226a982acc2e27faa57357705a1b4"
  git_remote: "https://github.com/openpipelines-bio/openpipeline"
