functionality:
  name: "rna_singlesample"
  namespace: "multiomics"
  description: "Processing unimodal single-sample RNA transcriptomics data."
  authors:
    - __merge__: ../../../src/authors/dries_de_maeyer.yaml
      roles: [ author ]
    - __merge__: ../../../src/authors/robrecht_cannoodt.yaml
      roles: [ author, maintainer ]
    - __merge__: ../../../src/authors/dries_schaumont.yaml
      roles: [ author ]
  argument_groups:
    - name: "Input"
      arguments:
        - name: "--id"
          required: true
          type: string
          description: ID of the sample.
          example: foo
        - name: "--input"
          type: file
          required: true
          description: Path to the sample.
          example: dataset.h5mu
    - name: "Output"
      arguments:
        - name: "--output"
          type: file
          required: true
          direction: output
          description: Destination path to the output.
          example: output.h5mu
    - name: "Filtering options"
      arguments:
        - name: "--min_counts"
          example: 200
          type: integer
          description: Minimum number of counts captured per cell.
        - name: "--max_counts"
          example: 5000000
          type: integer
          description: Maximum number of counts captured per cell.
  
        - name: "--min_genes_per_cell"
          type: integer
          example: 200
          description: Minimum of non-zero values per cell.
        - name: "--max_genes_per_cell"
          example: 1500000
          type: integer
          description: Maximum of non-zero values per cell.

        - name: "--min_cells_per_gene"
          example: 3
          type: integer
          description: Minimum of non-zero values per gene.

        - name: "--min_fraction_mito"
          example: 0
          type: double
          description: Minimum fraction of UMIs that are mitochondrial.
        - name: "--max_fraction_mito"
          type: double
          example: 0.2
          description: Maximum fraction of UMIs that are mitochondrial.
    - name: "Mitochondrial gene detection"
      arguments:
        - name: "--var_name_mitochondrial_genes"
          type: string
          required: false
          description: |
            In which .var slot to store a boolean array corresponding the mitochondrial genes.
        - name: "--var_gene_names"
          required: false
          example: "gene_symbol"
          type: string
          description: |
            .var column name to be used to detect mitochondrial genes instead of .var_names (default if not set).
            Gene names matching with the regex value from --mitochondrial_gene_regex will be identified
            as a mitochondrial gene.
        - name: --mitochondrial_gene_regex
          type: string
          description: |
            Regex string that identifies mitochondrial genes from --var_gene_names.
            By default will detect human and mouse mitochondrial genes from a gene symbol.
          required: false
          default: "^[mM][tT]-"
  resources:
    - type: nextflow_script
      path: main.nf
  test_resources:
    - type: nextflow_script
      path: main.nf
      entrypoint: test_wf
    - path: ../../../resources_test/pbmc_1k_protein_v3