name: "cellranger_postprocessing"
namespace: "workflows/ingestion"
scope: "public"
description: "Post-processing Cell Ranger datasets."
info:
  name: Cell Ranger post-processing
  test_dependencies:
    - name: from_10xh5_to_h5mu
      namespace: convert
scope: "public"
    - name: cellranger_postprocessing_test
      namespace: test_workflows/ingestion
scope: "public"
authors:
  - __merge__: /src/authors/angela_pisco.yaml
    roles: [ author ]
  - __merge__: /src/authors/robrecht_cannoodt.yaml
    roles: [ author, maintainer ]
argument_groups:
  - name: Inputs
    arguments:
      - name: "--id"
        required: true
        type: string
        description: ID of the sample.
        example: foo
      - type: file
        name: --input
        required: true
        example: "input.h5mu"
        description: Input h5mu file created by running Cell Ranger and converting its output to h5mu.
  - name: Outputs
    arguments:
      - name: "--output"
        type: file
        direction: output
        description: "The converted h5mu file."
  - name: Correction arguments
    arguments:
      - name: "--perform_correction"
        type: boolean_true
        description: Whether or not to run CellBender to perform count correction.
      - name: "--cellbender_epochs"
        type: integer
        description: Number of epochs to run CellBender for.
        default: 150
  - name: Filtering arguments
    arguments:
      - name: "--min_genes"
        type: integer
        example: 100
        description: Minimum number of counts required for a cell to pass filtering.
      - name: "--min_counts"
        type: integer
        example: 1000
        description: Minimum number of genes expressed required for a cell to pass filtering.
resources:
  - type: nextflow_script
    path: main.nf
    entrypoint: run_wf
  - type: file
    path: /src/workflows/utils/
dependencies:
  - name: correction/cellbender_remove_background
  - name: filter/filter_with_counts
  - name: filter/subset_h5mu
# test_dependencies:
#   - name: convert/from_10xh5_to_h5mu
test_resources:
  - type: nextflow_script
    path: test.nf
    entrypoint: test_wf
  - type: nextflow_script
    path: test.nf
    entrypoint: test_wf2
  - path: /resources_test/pbmc_1k_protein_v3
runners:
  - type: nextflow
