functionality:
  name: "souporcell"
  namespace: "genetic_demux"
  version: "integration_build"
  authors:
  - name: "Xichen Wu"
    roles:
    - "author"
    info:
      role: "Contributor"
      links:
        github: "wxicu"
        linkedin: "xichen-wu"
        orcid: "0009-0008-2168-4508"
      organizations:
      - name: "Helmholtz Munich"
        href: "https://www.helmholtz-munich.de"
        role: "Student Assistant"
  argument_groups:
  - name: "Input"
    arguments:
    - type: "file"
      name: "--fasta"
      description: "reference fasta file"
      info: null
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--bam"
      description: "cellranger bam"
      info: null
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--bam_index"
      description: "cellranger bam index"
      info: null
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--barcodes"
      description: "barcodes.tsv from cellranger"
      info: null
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "integer"
      name: "--clusters"
      description: "number cluster, tbd add easy way to run on a range of k"
      info: null
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "integer"
      name: "--ploidy"
      description: "ploidy, must be 1 or 2"
      info: null
      default:
      - 2
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "integer"
      name: "--min_alt"
      description: "min alt to use locus"
      info: null
      default:
      - 10
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "integer"
      name: "--min_ref"
      description: "min ref to use locus"
      info: null
      default:
      - 10
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "integer"
      name: "--max_loci"
      description: "max loci per cell, affects speed"
      info: null
      default:
      - 2048
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "integer"
      name: "--restarts"
      description: "number of restarts in clustering, when there are > 12 clusters\
        \ we recommend increasing this to avoid local minima"
      info: null
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--common_variants"
      description: "common variant loci or known variant loci vcf, must be vs same\
        \ reference fasta"
      info: null
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--known_genotypes"
      description: "known variants per clone in population vcf mode, must be .vcf\
        \ right now we dont accept gzip or bcf sorry"
      info: null
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--known_genotypes_sample_names"
      description: "which samples in population vcf from known genotypes option represent\
        \ the donors in your sample"
      info: null
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "boolean_true"
      name: "--skip_remap"
      description: "dont remap with minimap2 (not recommended unless in conjunction\
        \ with --common_variants"
      info: null
      direction: "input"
      dest: "par"
    - type: "boolean_true"
      name: "--ignore"
      description: "set to True to ignore data error assertions"
      info: null
      direction: "input"
      dest: "par"
  - name: "Output"
    arguments:
    - type: "file"
      name: "--output"
      alternatives:
      - "-o"
      description: "name of directory to place souporcell files"
      info: null
      example:
      - "souporcell_out"
      must_exist: true
      create_parent: true
      required: false
      direction: "output"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  resources:
  - type: "bash_script"
    path: "script.sh"
    is_executable: true
  - type: "file"
    path: "./src/workflows/utils/labels.config"
    dest: "nextflow_labels.config"
  description: "souporcell is a method for clustering mixed-genotype scRNAseq experiments\
    \ by individual."
  test_resources:
  - type: "bash_script"
    path: "test.sh"
    is_executable: true
  - type: "file"
    path: "../../../resources_test/demuxafy_test_data"
  - type: "file"
    path: "src/base/openpipelinetestutils"
    dest: "openpipelinetestutils"
  info: null
  status: "enabled"
  requirements:
    commands:
    - "ps"
  set_wd_to_resources_dir: false
platforms:
- type: "docker"
  id: "docker"
  image: "cumulusprod/souporcell:2022.12"
  target_organization: "openpipelines-bio"
  target_registry: "ghcr.io"
  target_tag: "integration_build"
  namespace_separator: "/"
  resolve_volume: "Automatic"
  chown: true
  setup_strategy: "ifneedbepullelsecachedbuild"
  target_image_source: "https://github.com/openpipelines-bio/openpipeline"
  entrypoint: []
  cmd: null
- type: "nextflow"
  id: "nextflow"
  directives:
    label:
    - "highmem"
    - "highcpu"
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      mem1gb: "memory = 1.GB"
      mem2gb: "memory = 2.GB"
      mem4gb: "memory = 4.GB"
      mem8gb: "memory = 8.GB"
      mem16gb: "memory = 16.GB"
      mem32gb: "memory = 32.GB"
      mem64gb: "memory = 64.GB"
      mem128gb: "memory = 128.GB"
      mem256gb: "memory = 256.GB"
      mem512gb: "memory = 512.GB"
      mem1tb: "memory = 1.TB"
      mem2tb: "memory = 2.TB"
      mem4tb: "memory = 4.TB"
      mem8tb: "memory = 8.TB"
      mem16tb: "memory = 16.TB"
      mem32tb: "memory = 32.TB"
      mem64tb: "memory = 64.TB"
      mem128tb: "memory = 128.TB"
      mem256tb: "memory = 256.TB"
      mem512tb: "memory = 512.TB"
      cpu1: "cpus = 1"
      cpu2: "cpus = 2"
      cpu5: "cpus = 5"
      cpu10: "cpus = 10"
      cpu20: "cpus = 20"
      cpu50: "cpus = 50"
      cpu100: "cpus = 100"
      cpu200: "cpus = 200"
      cpu500: "cpus = 500"
      cpu1000: "cpus = 1000"
    script:
    - "includeConfig(\"nextflow_labels.config\")"
  debug: false
  container: "docker"
info:
  config: "/home/runner/work/openpipeline/openpipeline/src/genetic_demux/souporcell/config.vsh.yaml"
  platform: "nextflow"
  output: "/home/runner/work/openpipeline/openpipeline/target/nextflow/genetic_demux/souporcell"
  executable: "/home/runner/work/openpipeline/openpipeline/target/nextflow/genetic_demux/souporcell/souporcell"
  viash_version: "0.8.5"
  git_commit: "4aa7186bf5510873a069a4f76d65b36124916c2b"
  git_remote: "https://github.com/openpipelines-bio/openpipeline"
